<div class="mw-osc-title-login">
	<h1><?php echo __('Forgot Your Password?') ?></h1>
</div>
<?php echo $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
<form method="post" id="form-validate">
	<div class="fieldset">
		<p><?php echo __('Please enter your email address below. You will receive a link to reset your password.')?></p>
		<ul class="form-list">
			<li>
				<label for="email_address" class="required"><?php echo __('Email Address');?><em>*</em></label>
				<div class="input-box">
					<input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" />
					<div id="errorforgotpass" class="validation-advice"><?php echo __('Invalid email!');?></div>
				</div>
			</li>
		</ul>
	</div>
	<div class="buttons-set">
		<p class="required"><?php echo __('* Required Fields') ?></p>
		<p class="back-link"><a id="backlogin" href="#inline1"><small>&laquo; </small><?php echo __('Back to Login') ?></a></p>
		<span id="forgotpass-please-wait" class="please-wait">
			<img class="v-middle" title="Loading next step..." alt="Loading next step..." src="<?php echo $block->getViewFileUrl('MW_Onestepcheckout::images/opc-ajax-loader.gif') ?>"><?php echo __('Loading...');?>
		</span>
		<button id="btforgotpass" type="button" title="<?php echo __('Submit') ?>" class="button"><span><span><?php echo __('Submit') ?></span></span></button>
	</div>
</form>
