<div class="col2-set">
	<?php echo $block->getChildHtml('login_before')?>
	<div class="col-2">
		<div class="mw-osc-title-login">
			<h1><?php echo __('Login') ?></h1>
		</div>
		<?php echo $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
		<form id="mw-login-form" method="post">
			<input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>" />
			<fieldset>
				<div class="fieldset">
					<p style="color:black; font-weight:bold;"><?php echo __('If you have an account with us, please log in.') ?></p>
					<div id="errorlogin"><p style="color:red; font-weight:bold;"><?php echo __('Invalid email or password!');?></p></div>
					<ul class="form-list">
						<li>
							<label for="mw-login-email" class="required"><?php echo __('Email Address') ?><em>*</em></label>
							<div class="input-box">
								<input type="text" class="input-text required-entry validate-email" id="mw-login-email" name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" />
							</div>
						</li>
						<li>
							<label for="mw-login-password" class="required"><?php echo __('Password') ?><em style="position:static;float:none;color:#EB340A;font-style:normal;right:-8px;top:0;">*</em></label>
							<div class="input-box">
								<input type="password" class="input-text required-entry" id="mw-login-password" name="login[password]" />
							</div>
						</li>
					</ul>
				</div>
	            <div class="clear"></div>
	                <div class="other_login">
	                <span class="ol_text"><?php echo __('Or Login via') ?></span>
	                <div class="ol-img" id="login_fb"></div>
	            </div>
				<div class="col-2" style="float:none;">
					<div class="buttons-set">
						<p class="required"><?php echo __('* Required Fields') ?></p>
						<a id="forgotpassword" href="#inline3" class="f-left"><?php echo __('Forgot your password?') ?></a>
	                    <div class="clear"></div>
						<span id="mw-login-please-wait" class="please-wait">
							<img class="v-middle" title="Loading next step..." alt="Loading next step..." src="<?php echo $block->getViewFileUrl('MW_Onestepcheckout::images/opc-ajax-loader.gif') ?>"><?php echo __(' Loading...') ?>
						</span>
						<button type="button" class="button btn-login"><span><span><?php echo __('Login') ?></span></span></button>
					</div>
				</div>
			</fieldset>
		</form>
	</div>
    <!-- end.col2-set -->
    <div class="clear"></div>
    <div id="fb-root"></div>
</div>