<div id="co-shipping-method-form">
    <div class="mw-osc-block-content">
        <div id="checkout-shipping-method-load">
            <?php echo $block->getChildHtml('available') ?>
        </div>
    </div>

    <?php
        $_dataHelper = $this->helper('MW\Onestepcheckout\Helper\Data');
        if($_dataHelper->getStoreConfig("onestepcheckout/deliverydate/allow_options")) {
            echo $block->getChildHtml('deliverydate');
        }
    ?>
</div>
