<?php
    $_dataHelper = $this->helper('MW\Onestepcheckout\Helper\Data');
?>
<div id="co-shipping-form">
	<ul class="form-list">
	<?php if ($block->customerHasAddresses() && $_dataHelper->showAddressBook()) : ?>
	   <li class="wide">
		   <label for="shipping-address-select"><?php echo __('Select a shipping address from your address book or enter a new address.') ?></label>
		   <div class="input-box">
			   <?php echo $block->getAddressesHtmlSelect('shipping') ?>
		   </div>
	   </li>
	<?php endif; ?>			
		<li id="shipping-new-address-form">
            <input type="hidden" name="shipping[address_id]" value="<?php echo $block->getAddress()->getId() ?>" id="shipping:address_id" />
            <ul>
                <div id="mw_onstepcheckout_shipping_form">
                    <?php echo $block->getChildHtml('sortshipping');?>
                </div>
                
                <?php if ($block->isCustomerLoggedIn() && $block->customerHasAddresses() && $_dataHelper->showAddressBook()) : ?>
                    <li class="control">
                        <input type="checkbox" name="shipping[save_in_address_book]" value="0" title="<?php echo __('Save in address book') ?>" id="shipping:save_in_address_book" <?php if ($block->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
                        <label for="shipping:save_in_address_book"><?php echo __('Save in address book') ?></label>
                    </li>
                <?php elseif ($block->isCustomerLoggedIn() && $block->customerHasAddresses() && !$_dataHelper->showAddressBook()) : ?>
                    <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="0" /></li>
                <?php else : ?>
                    <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                <?php endif;?>
            </ul>
            <div class="clear"></div>
            <li class="control samebilling">
                <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if ($block->getAddress()->getSameAsBilling()) : ?> checked="checked"<?php endif; ?> title="<?php echo __('Use Billing Address') ?>" class="checkbox" /><label for="shipping:same_as_billing" style="float:none;"><?php echo __('Use Billing Address') ?></label>
            </li>
		</li>
	</ul>
</div>