<?php
/**
 * Cart2Quote
 */

/** @var $block \Magento\Checkout\Block\Item\Price\Renderer */
?>
<?php
$_item = $block->getItem();
$checkoutHelper = $this->helper('Magento\Checkout\Helper\Data');
?>
<div class="price-container">
    <span class="price-label"><?php echo __('Price') ?></span>
    <span class="price-wrapper"><?php echo $checkoutHelper->formatPrice($_item->getCalculationPrice()) ?></span>
</div>
