<?php 
$_order = $block->getCurrentOrder();
if ($_order) :
?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
		<span class="title"><?php echo __('Delivery Date') ?></span>
	</div>
	<div class="admin__page-section-item-content">
		<?php echo __('Delivery Date:')?><span style="font-weight:bold;"> <?php echo $_order->getMwDeliverydateDate(); ?></span>
		<br />
		<?php echo __('Delivery Time:')?><span style="font-weight:bold;"> <?php echo $_order->getMwDeliverydateTime(); ?></span>
	</div>
</div>
<?php endif; ?>