<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>

<?php if ($listing = $block->getListing()): ?>
    <?php $amazonName = $listing->getName() ?>
    <?php $magentoSku = $listing->getCatalogSku() ?>
    <?php $amazonSku = $listing->getSellerSku() ?>
    <div>
        <p><b><?= $block->escapeHtml(__(' Listing Details ')) ?></b></p>
        <br>
        <div class="listing-details">
            <p><?= $block->escapeHtml(__('Amazon Name:  ' . $block->escapeHtml($amazonName))) ?></p>
            <br>
            <p><?= $block->escapeHtml(__('Catalog (Magento) SKU:  ' . $block->escapeHtml($magentoSku))) ?></p>
            <br>
            <p><?= $block->escapeHtml(__('Amazon Seller SKU:  ' . $block->escapeHtml($amazonSku))) ?></p>
            <br>
        </div>
    </div>
<?php endif ?>