<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="general-info">
    <div class="help-and-general-form">
        <?= $block->escapeHtml(__('Displays all suggested listing improvements provided by Amazon for this marketplace')) ?>
    </div>
    <div class="help-button">
        <button type="button"
                class="action-default"
                onclick="window.open('<?= $block->getUserGuideUrl() . $block->getReportDefectUrl() ?>', '_blank')"
                id="helpButton" >
            <span><?= $block->escapeHtml(__('View User Guide')) ?></span>
        </button>
    </div>
</div>

