<?php
$imagesJson = $block->getGalleryImagesJson();
$imagesArray = json_decode($imagesJson);
$thumbwidth = $block->getImageAttribute('product_page_image_small', 'width');
$thumbheight = $block->getImageAttribute('product_page_image_small', 'height');
$viewModel = $block->getViewModel();
$imagesJson = $viewModel->getJsonWithMainImage($imagesJson);
$mainThumbHtml = $viewModel->getMainThumbHtml($imagesJson, $thumbwidth);
$mainImage = $viewModel->getMainImage($imagesJson);
?>
<style>
    .fotorama-item .fotorama__nav--thumbs .fotorama__nav__frame {
        padding: 2px;
        height: <?php echo $thumbheight;?>px
    }

    .fotorama-item .fotorama__thumb-border {
        height: <?php echo $thumbheight;?>px;
        border-width: 2px;
        margin-top: 2px
    }
</style>
<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <div class="fotorama-item" data-gallery-role="gallery">
        <div data-gallery-role="fotorama__focusable-start" tabindex="-1"></div>
        <div class="fotorama__wrap fotorama__wrap--css3 fotorama__wrap--slide fotorama__wrap--toggle-arrows">
            <div class="fotorama__stage" data-fotorama-stage="fotorama__stage">
                <div class="fotorama__arr fotorama__arr--prev"
                     tabindex="0"
                     role="button"
                     aria-label="Previous"
                     data-gallery-role="arrow">
                    <div class="fotorama__arr__arr"></div>
                </div>
                <div class="fotorama__stage__shaft" tabindex="0" data-gallery-role="stage-shaft">
                    <div class="fotorama__stage__frame fotorama__active fotorama_vertical_ratio fotorama__loaded fotorama__loaded--img"
                         aria-hidden="false" data-fotorama-backend-image="true" data-active="true" style="left: 0px;"
                         href="<?php echo $mainImage['img']; ?>">
                        <img src="<?php echo $mainImage['img']; ?>" alt="<?php echo $mainImage['caption']; ?>"
                             class="fotorama__img" aria-hidden="false">
                    </div>
                    <div class="magnifier-preview" data-gallery-role="magnifier" id="preview"></div>
                </div>
                <div class="fotorama__arr fotorama__arr--next fotorama__arr--disabled"
                     tabindex="-1"
                     role="button"
                     aria-label="Next"
                     data-gallery-role="arrow">
                    <div class="fotorama__arr__arr"></div>
                </div>
                <div class="fotorama__video-close"></div>
                <div class="fotorama__zoom-in" data-gallery-role="fotorama__zoom-in" aria-label="Zoom in" role="button"
                     tabindex="0"></div>
                <div class="fotorama__zoom-out" data-gallery-role="fotorama__zoom-out" aria-label="Zoom out"
                     role="button" tabindex="0"></div>
                <!-- <div class="fotorama__spinner"></div> -->
            </div>
            <div class="fotorama__nav-wrap" data-gallery-role="nav-wrap">
                <div class="fotorama__nav fotorama__nav--thumbs">
                    <div class="fotorama__fullscreen-icon"
                         data-gallery-role="fotorama__fullscreen-icon"
                         tabindex="0"
                         aria-label="Exit fullscreen"
                         role="button">
                    </div>
                    <div class="fotorama__thumb__arr fotorama__thumb__arr--left fotorama__arr--disabled"
                         role="button"
                         aria-label="Previous"
                         data-gallery-role="arrow"
                         tabindex = "-1">
                        <div class="fotorama__thumb--icon"></div>
                    </div>
                    <div class="fotorama__nav__shaft">
                    </div>
                    <div class="fotorama__thumb__arr fotorama__thumb__arr--right fotorama__arr--disabled"
                         role="button"
                         aria-label="Next"
                         data-gallery-role="arrow"
                         tabindex = "-1">
                        <div class="fotorama__thumb--icon"></div>
                    </div>
                </div>
            </div>
        </div>
        <div data-gallery-role="fotorama__focusable-end" tabindex="-1"></div>
    </div>
</div>
<script>
    var config = {
            "width": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
            "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')
                ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
            "navtype": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navtype"); ?>",
            "height": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'height'); ?>
        },
        thumbBarHeight = 0,
        loader = document.querySelectorAll('[data-gallery-role="gallery-placeholder"] [data-role="loader"]')[0];

    if (config.navtype === 'horizontal') {
        thumbBarHeight = config.thumbheight;
    }

    var width = document.getElementsByClassName('fotorama-item')[0].offsetWidth;
    var ratio = config.width / config.height;
    var height = Math.round(width / ratio);
    document.getElementsByClassName('fotorama__stage')[0].setAttribute('style','width: '+width+'px;height: '+height+'px');
    var data_ = <?php /* @escapeNotVerified */ echo $imagesJson; ?>;
</script>

<script type="text/x-magento-init">
        {
            "[data-gallery-role=gallery-placeholder]": {
                "Xumulus_FastGalleryLoad/js/gallery/custom_gallery": {
                    "mixins":["magnifier/magnify"],
                    "magnifierOpts": <?php /* @escapeNotVerified */
    echo $block->getMagnifier(); ?>,
                    "data": <?php /* @escapeNotVerified */
    echo $imagesJson; ?>,
                    "options": {
                        "nav": "<?php /* @escapeNotVerified */
    echo $block->getVar("gallery/nav"); ?>",
                        <?php if (($block->getVar("gallery/loop"))): ?>
                            "loop": <?php /* @escapeNotVerified */
        echo $block->getVar("gallery/loop"); ?>,
                        <?php endif; ?>
                        <?php if (($block->getVar("gallery/keyboard"))): ?>
                            "keyboard": <?php /* @escapeNotVerified */
        echo $block->getVar("gallery/keyboard"); ?>,
                        <?php endif; ?>
                        <?php if (($block->getVar("gallery/arrows"))): ?>
                            "arrows": <?php /* @escapeNotVerified */
        echo $block->getVar("gallery/arrows"); ?>,
                        <?php endif; ?>
                        <?php if (($block->getVar("gallery/allowfullscreen"))): ?>
                            "allowfullscreen": <?php /* @escapeNotVerified */
        echo $block->getVar("gallery/allowfullscreen"); ?>,
                        <?php endif; ?>
                        <?php if (($block->getVar("gallery/caption"))): ?>
                            "showCaption": <?php /* @escapeNotVerified */
        echo $block->getVar("gallery/caption"); ?>,
                        <?php endif; ?>
                        "width": "<?php /* @escapeNotVerified */
    echo $block->getImageAttribute('product_page_image_medium', 'width'); ?>",
                        "thumbwidth": "<?php /* @escapeNotVerified */
    echo $block->getImageAttribute('product_page_image_small', 'width'); ?>",
                        <?php if ($block->getImageAttribute('product_page_image_small', 'height') || $block->getImageAttribute('product_page_image_small', 'width')): ?>
                            "thumbheight": <?php /* @escapeNotVerified */
        echo $block->getImageAttribute('product_page_image_small', 'height')
            ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                        <?php endif; ?>
                        <?php if ($block->getImageAttribute('product_page_image_medium', 'height') || $block->getImageAttribute('product_page_image_medium', 'width')): ?>
                            "height": <?php /* @escapeNotVerified */
        echo $block->getImageAttribute('product_page_image_medium', 'height')
            ?: $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
                        <?php endif; ?>
                        <?php if ($block->getVar("gallery/transition/duration")): ?>
                            "transitionduration": <?php /* @escapeNotVerified */
        echo $block->getVar("gallery/transition/duration"); ?>,
                        <?php endif; ?>
                        "transition": "<?php /* @escapeNotVerified */
    echo $block->getVar("gallery/transition/effect"); ?>",
                        <?php if (($block->getVar("gallery/navarrows"))): ?>
                            "navarrows": <?php /* @escapeNotVerified */
        echo $block->getVar("gallery/navarrows"); ?>,
                        <?php endif; ?>
                        "navtype": "<?php /* @escapeNotVerified */
    echo $block->getVar("gallery/navtype"); ?>",
                        "navdir": "<?php /* @escapeNotVerified */
    echo $block->getVar("gallery/navdir"); ?>"
                    },
                    "fullscreen": {
                        "nav": "<?php /* @escapeNotVerified */
    echo $block->getVar("gallery/fullscreen/nav"); ?>",
                        <?php if ($block->getVar("gallery/fullscreen/loop")): ?>
                            "loop": <?php /* @escapeNotVerified */
        echo $block->getVar("gallery/fullscreen/loop"); ?>,
                        <?php endif; ?>
                        "navdir": "<?php /* @escapeNotVerified */
    echo $block->getVar("gallery/fullscreen/navdir"); ?>",
                        <?php if ($block->getVar("gallery/transition/navarrows")): ?>
                            "navarrows": <?php /* @escapeNotVerified */
        echo $block->getVar("gallery/fullscreen/navarrows"); ?>,
                        <?php endif; ?>
                        "navtype": "<?php /* @escapeNotVerified */
    echo $block->getVar("gallery/fullscreen/navtype"); ?>",
                        <?php if ($block->getVar("gallery/fullscreen/arrows")): ?>
                            "arrows": <?php /* @escapeNotVerified */
        echo $block->getVar("gallery/fullscreen/arrows"); ?>,
                        <?php endif; ?>
                        <?php if ($block->getVar("gallery/fullscreen/caption")): ?>
                            "showCaption": <?php /* @escapeNotVerified */
        echo $block->getVar("gallery/fullscreen/caption"); ?>,
                        <?php endif; ?>
                        <?php if ($block->getVar("gallery/fullscreen/transition/duration")): ?>
                            "transitionduration": <?php /* @escapeNotVerified */
        echo $block->getVar("gallery/fullscreen/transition/duration"); ?>,
                        <?php endif; ?>
                        "transition": "<?php /* @escapeNotVerified */
    echo $block->getVar("gallery/fullscreen/transition/effect"); ?>"
                    },
                    "breakpoints": <?php /* @escapeNotVerified */
    echo $block->getBreakpoints(); ?>
                }
            }
        }

</script>

