<?php
/**
 * Copyright © 2016 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php
/** @var \MageWorx\Downloads\Block\Catalog\Product\Link $block */

$item     = $block->getItem();
$fileName = $item->getName();
$codeFileName = $item->getFilename();
$itemUrl  = $block->getAttachmentLink($item->getId(), $codeFileName);
?>

<div class="downloads-item">
    <div class="item-link">
        <?php if ($item->getIsInGroup()) { ?>
            <span>
                <a href="<?php echo $block->escapeHtml($itemUrl) ?>"
                   rel="<?php echo $item->getId() ?>"
                   target="_blank"
                   title="<?php echo $block->escapeHtml($item->getName()) ?>">
                <?php echo $block->escapeHtml($item->getName()) ?>
                </a>
                <span><?php echo strtoupper($block->escapeHtml('('. $item->getType() . ')')) ?></span>
            </span>
        <?php } else { ?>
            <b><?php echo $fileName ?></b><span>*</span>
        <?php } ?>
    </div>
</div>
