<?php /** @var \CanadaSatellite\Theme\Block\Catalog\Product\Attachments $block */ ?>
<?php $attachments = $block->getAttachments(); ?>
<?php if ($attachments) : ?>
<tr>
    <td class = "downloads-attachments" colspan="5">
        <p>Downloadable attachments:</p>
        <div class="product-attachment-container">

            <?php foreach ($attachments as $attachment): ?>
                <?php echo $block->getAttachmentHtml($attachment); ?>
            <?php endforeach; ?>

            <?php if ($block->isShowHowToDownloadMessage()): ?>
                <div class="access-notice"><span>* <?php echo $block->getHowToDownloadMessage() ?></span></div>
            <?php endif; ?>

        </div>
    </td>
</tr>
<?php endif; ?>
