<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Select */ ?>
<?php $_option      = $block->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>
<div class="field option <?php echo ($_option->getRequired()) ? ' required': ''; ?>">
    <label class="label" for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>">
        <span><?php echo $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <?php if ($block->showSingle()): ?>
            <?php if (!$_canChangeQty):?>
                <span class="qty_selected">
                    <?php echo __('%1 of',$_defaultQty);?>
                </span>
            <?php endif;?>
            <span class="product-name">
                <a onclick="window.open('<?php echo $this->getUrl('casat/index/bundlesimpleview/id/'.$_selections[0]->getProductId());?>', 'bundle_popup', 'menubar=no,toolbar=no,location=no,width=780,height=560')"
                   target="_blank"
                   href="<?php echo substr($this->getUrl($_selections[0]->getUrlKey() . '.htm'), 0, -1);?>">
                   <?php echo $block->escapeHtml($_selections[0]->getName()); ?>
                </a>
            </span>
            &nbsp; <span class="price-notice">(<?php echo trim($block->renderPriceString($_selections[0], true)); ?>)</span>
            <input type="hidden"
                   class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                   name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                   value="<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>"/>
        <?php else:?>
            <select id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>"
                    name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                    data-selector="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                    class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?> product bundle option bundle-option-select change-container-classname"
                <?php if ($_option->getRequired()) echo 'data-validate = {required:true}' ?>>
                <option value=""><?php /* @escapeNotVerified */ echo __('Choose a selection...') ?></option>
                <?php foreach ($_selections as $_selection): ?>
                    <option value="<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"
                        <?php if ($block->isSelected($_selection)) echo ' selected="selected"' ?>
                        <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>>
                        <?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>
        <div class="nested<?php if (!$_canChangeQty) echo ' qty-disabled' ?>">
            <div class="field qty qty-holder">
                <label class="label" for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input">
                    <span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span>
                </label>
                <div class="control">
                    <input <?php if (!$_canChangeQty) echo ' disabled="disabled"' ?>
                           id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input"
                           class="input-text qty<?php if (!$_canChangeQty) echo ' qty-disabled' ?>"
                           type="number"
                           name="bundle_option_qty[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           data-selector="bundle_option_qty[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           value="<?php /* @escapeNotVerified */ echo $_defaultQty ?>"/>
                </div>
            </div>
        </div>
    </div>
</div>
