<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2016] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Cart2Quote
 * @package     Desk
 * @copyright   Copyright (c) 2016 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var Cart2Quote\Desk\Block\Customer\Ticket\View\Message $block */
?>

<?php $ticket = $block->getTicketData() ?>
<div class="ticket-subject">
    <div class="ticket-subject-value special-title">
        <input name="ticket[subject]"
               type="text"
               value="<?php echo $ticket->getSubject()?>"
               placeholder="<?php echo __("The Subject") ?>"
               id="ticket-subject"
               class="input-text required-entry" />
    </div>
</div>
<div class="create-message">
        <textarea name="message[message]"
                  id="comment"
                  title="What’s on your mind?"
                  class="input-text"
                  cols="5" rows="3"
                  data-validate="{required:true}"
                  aria-required="true"
                  placeholder="<?php echo __("Enter your message") ?>"></textarea>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="">
            <button type="submit" title="Submit" class="action submit primary" id="send-message-button">
                <span><?php echo __("Send") ?></span>
            </button>
        </div>
    </div>
</div>
