<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$config = $objectManager->create('CanadaSatellite\Theme\Model\Config\Config');
?>
<div id="topfooter" class="top-footer-wrapper">
	<div class="footer content footer-content-top">
		<div class="widget block block-static-block">
			<div class="footer-top-ads text-center container">
				<div class="newsletter-title"><h3>Keep in Touch!</h3></div>
				<div class="ftop-newsletter">
					<div class="block newsletter">
						<div class="title"><strong>Newsletter</strong></div>
						<div class="content">
							<form class="form subscribe"
								  novalidate
								  action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
								  method="post"
								  data-mage-init='{"validation": {"errorClass": "mage-error"}}'
								  id="newsletter-validate-detail">
								<div class="input-newleter">
									<div class="field newsletter">
										<label class="label" for="newsletter"><span>Sign Up for Our Newsletter:</span></label>
										<div class="control">
											<input name="email" type="email" id="newsletter"
												   placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
												   data-validate="{required:true, 'validate-email':true}"/>
										</div>
                                        <input type="hidden" name="recaptcha_response_v3_news" id="recaptchaResponseV3News">
									</div>
									<div class="actions">
										<button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
											<span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
										</button>
									</div>
								</div>

							</form>
						</div>
					</div>
				</div>
				<div class="social-section">
					<ul class="social-link-list">
						<li class="facebook"><a href="https://www.facebook.com/Canada-Satellite-458948160804947/">facebook</a>
						</li>
						<li class="twitter"><a href="https://twitter.com/CanadaSat">twitter</a></li>
						<li class="youtube"><a href="https://www.youtube.com/channel/UCOpTAVmYMXCrlSzPWz-MX-g">youtube</a></li>
					</ul>
				</div>
				<div class="clearboth">&nbsp;</div>

			</div>
		</div>

        <div class="footer-country-links">
            <span style="font-family: helvetica; font-size: large;">
                <a title="Africa Satellite" href="https://www.africasatellite.com/" target="_self">AFRICA</a> |
                <a title="Australia Satellite" href="https://www.asiasatellite.co/" target="_self">ASIA</a> |
                <a title="Australia Satellite" href="https://www.australiasatellite.co/" target="_self">AUSTRALIA</a> |
                <a title="Canada Satellite" href="https://www.canadasatellite.ca/" target="_self">CANADA</a> |
                <a title="Europa Satellite" href="https://www.europasatellite.com/" target="_self">EUROPE</a> |
                <a title="USA" href="https://www.americansatellite.us/" target="_self">USA</a>
            </span>
        </div>

	</div>
</div>

<script type="text/javascript">
    requirejs(['jquery'], function ($) {

        recaptchaScriptNewsAdded = false;

        jQuery('#newsletter').focus(function () {
            loadMainRecaptchaScript();
            if (!recaptchaScriptNewsAdded) {
                var recaptchaFormScript = document.createElement('script');
                recaptchaFormScript.innerHTML = "var recaptchaInt = setInterval(function(){if (typeof(grecaptcha)=='undefined'){return;}clearInterval(recaptchaInt);grecaptcha.ready(function(){grecaptcha.execute('<?php echo $config->getPublicKey() ?>',{ action: 'contact' }).then(function (token) {var recaptchaResponse = document.getElementById('recaptchaResponseV3News');recaptchaResponse.value = token});});},50);";
                jQuery('#maincontent').after(recaptchaFormScript);
                recaptchaScriptNewsAdded = true;
            }
        });
    });
</script>
   
