<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="dashboard-container row">
    <?= $block->getChildHtml('amazon_account_listing_details_edit_tabs') ?>
    <?php if (is_array($block->getChildBlock('amazon_account_listing_details_edit_tabs')->getTabsIds())) : ?>
        <div id="amazon_account_listing_details_index" class="amazon_account_listing_details_index"></div>
    <?php endif; ?>
</div>
