<?php
use Magento\Catalog\Model\Product as P;
use Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer as B;
use Magento\Sales\Model\Order\Item as OI;
/** @var B $block */ $b = $block; /** @var B $b */
$i = $b->getItem(); /** @var OI $i */
?>
<tr id="order-item-row-<?= $i->getId() ?>">
	<td class="col name" data-th="<?= $b->escapeHtml(__('Product Name')) ?>">
<?php
# 2021-06-24 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
# «Call to a member function getProductUrl() on null
# in app/design/frontend/MageSuper/magestylish/Magento_Sales/templates/order/items/renderer/default.phtml:14»:
# https://github.com/canadasatellite-ca/site/issues/182
?>
		<?php if ($p = $i->getProduct()) { /** @var P $p */ ?>
			<a href="<?php echo $b->escapeHtml($p->getProductUrl()) ?>">
				<strong class="product name product-item-name"><?= $b->escapeHtml($i->getName()) ?></strong>
			</a>
		<?php } ?>
		<?php if ($_options = $b->getItemOptions()): ?>
		<dl class="item-options">
		<?php foreach ($_options as $_option) : ?>
			<dt><?= $b->escapeHtml($_option['label']) ?></dt>
			<?php if (!$b->getPrintStatus()): ?>
				<?php $_formatedOptionValue = $b->getFormatedOptionValue($_option) ?>
				<dd>
					<?php if (isset($_formatedOptionValue['full_view'])): ?>
						<?= $_formatedOptionValue['full_view'] ?>
					<?php else: ?>
						<?= $_formatedOptionValue['value'] ?>
					<?php endif; ?>
				</dd>
			<?php else: ?>
				<dd>
					<?= nl2br($b->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
				</dd>
			<?php endif; ?>
		<?php endforeach; ?>
		</dl>
		<?php endif; ?>
		<?php $addtInfoBlock = $b->getProductAdditionalInformationBlock(); ?>
		<?php if ($addtInfoBlock) :?>
			<?= $addtInfoBlock->setItem($i)->toHtml() ?>
		<?php endif; ?>
		<?= $b->escapeHtml($i->getDescription()) ?>
	</td>
	<td class="col sku" data-th="<?= $b->escapeHtml(__('SKU')) ?>"><?= $b->prepareSku($b->getSku()) ?></td>
	<td class="col price" data-th="<?= $b->escapeHtml(__('Price')) ?>">
		<?= $b->getItemPriceHtml() ?>
	</td>
	<td class="col qty" data-th="<?= $b->escapeHtml(__('Qty')) ?>">
		<ul class="items-qty">
		<?php if ($b->getItem()->getQtyOrdered() > 0): ?>
			<li class="item">
				<span class="title"><?= __('Ordered') ?></span>
				<span class="content"><?= $b->getItem()->getQtyOrdered()*1 ?></span>
			</li>
		<?php endif; ?>
		<?php if ($b->getItem()->getQtyShipped() > 0): ?>
			<li class="item">
				<span class="title"><?= __('Shipped') ?></span>
				<span class="content"><?= $b->getItem()->getQtyShipped()*1 ?></span>
			</li>
		<?php endif; ?>
		<?php if ($b->getItem()->getQtyCanceled() > 0): ?>
			<li class="item">
				<span class="title"><?= __('Canceled') ?></span>
				<span class="content"><?= $b->getItem()->getQtyCanceled()*1 ?></span>
			</li>
		<?php endif; ?>
		<?php if ($b->getItem()->getQtyRefunded() > 0): ?>
			<li class="item">
				<span class="title"><?= __('Refunded') ?></span>
				<span class="content"><?= $b->getItem()->getQtyRefunded()*1 ?></span>
			</li>
		<?php endif; ?>
		</ul>
	</td>
	<td class="col subtotal" data-th="<?= $b->escapeHtml(__('Subtotal')) ?>">
		<?= $b->getItemRowTotalHtml() ?>
	</td>
</tr>