<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= $block->escapeHtml($block->getMethodCode()) ?>" style="display: none">
    <div class="admin__field _required">
        <label for="po_number" class="admin__field-label"><span><?= $block->escapeHtml(__('Amazon Invoice Number')) ?></span></label>
        <div class="admin__field-control">
            <input type="text" id="po_number" name="payment[po_number]"
                   title="<?= $block->escapeHtml(__("Amazon Invoice Number")) ?>" class="required-entry admin__control-text"
                   value="<?php /* @noEscape */ echo $block->getInfoData('po_number') ?>"/>
        </div>
    </div>
</fieldset>
