<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php $first = true; ?>
<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else:?>
    <tr class="<?= /* @escapeNotVerified */ $_code ?>">

        <?php if ($first) :?>
            <th class="taxvat" style="text-align: left">GST / HST #775933914</th>
            <?php if ($block->getLabelProperties() === 'colspan="4" class="mark"') : ?>
                <th scope="row" colspan="3" style="text-align: right">
            <?php else:?>
                <th scope="row">
            <?php endif?>
            <?php $first = false; ?>
        <?php else:?>
            <th <?= /* @escapeNotVerified */ $block->getLabelProperties() ?> scope="row">
        <?php endif?>

            <?php if ($_total->getStrong()):?>
                <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
            <?php else:?>
                <?= $block->escapeHtml($_total->getLabel()) ?>
            <?php endif?>
        </th>

        <td <?= /* @escapeNotVerified */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtml($_total->getLabel()) ?>">
            <?php if ($_total->getStrong()):?>
            <strong><?= /* @escapeNotVerified */ $block->formatValue($_total) ?></strong>
            <?php else:?>
            <?= /* @escapeNotVerified */ $block->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif?>
<?php endforeach?>
