<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Aheadworks\AdvancedReviews\Block\Reviews\Page\Container */
?>
<div data-role="aw-ar-product-view-review-container" data-bind="scope: 'awArReviewContainer'" class="all-customer-reviews">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script>
    window.awAr = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
</script>
<script type="text/x-magento-init">
{

    "[data-role=aw-ar-product-view-review-container]": {
        "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout() ?>
    }
}
</script>

