<?php echo $block->getChildHtml('items_before'); ?>
<?php
$_dataHelper = $this->helper('MW\Onestepcheckout\Helper\Data');
$_taxHelper = $this->helper('Magento\Tax\Helper\Data');
?>
<div id="checkout-review-table-wrapper">
    <table class="data-table" id="checkout-review-table">
	<?php if ($_dataHelper->getStoreConfig("onestepcheckout/general/allowremoveproduct")) : ?>
		<col width="1" />
	<?php endif; ?>	
	<?php if ($_dataHelper->showImageProduct()) : ?>
		<col width="1" />
	<?php endif; ?>
        <?php
            if ($_taxHelper->displayCartBothPrices()) {
                $colspan = $rowspan = 2;
            } else {
                $colspan = $rowspan = 1;
            }
        ?>
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <?php if ($_taxHelper->displayCartBothPrices()) : ?>
        <col width="1" />
        <col width="1" />
        <?php endif; ?>
        <thead>
            <tr>
			<?php if ($_dataHelper->getStoreConfig("onestepcheckout/general/allowremoveproduct")) : ?>
				<th></th>
			<?php endif?>
			<?php if ($_dataHelper->showImageProduct()) : ?>
				<th class="ost-item-image"></th>
			<?php endif?>
                <th rowspan="<?php echo $rowspan ?>"><?php echo __('Product Name') ?></th>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo __('Price') ?></th>
                <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo __('Qty') ?></th>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo __('Subtotal') ?></th>
            </tr>
            <?php if ($_taxHelper->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-right"><?php echo $_taxHelper->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $_taxHelper->getIncExcTaxLabel(true) ?></th>
                    <th class="a-right"><?php echo $_taxHelper->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $_taxHelper->getIncExcTaxLabel(true) ?></th>
                </tr>
            <?php endif; ?>
        </thead>
        <?php echo $block->getChildHtml('totals'); ?>
        <tbody>
        <?php foreach ($block->getItems() as $_item) : ?>
            <?php echo $block->getItemHtml($_item); ?>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php
        $giftWrap = $_dataHelper->getStoreConfig('onestepcheckout/addfield/price_gift_wrap');
        if ($giftWrap != '' && (int) $giftWrap > 0) :
            if ($_dataHelper->getSessionManager()->getIsWrap()) {
                $isWrap = 'checked="checked"';
            } else {
                $isWrap = '';
            }
    ?>
        <div class="onestepcheckout-gift-wrap">
            <input type="checkbox" id="id_gift_wrap" name="gift_wrap" value="1" <?php echo $isWrap ?> />
            <label for="id_gift_wrap"><?php echo __('Gift Wrap') ?></label>
        </div>
    <?php endif; ?>
</div>