<?php
$_item = $block->getItem();
$_dataHelper = $this->helper('MW\Onestepcheckout\Helper\Data');
$_taxHelper = $this->helper('Magento\Tax\Helper\Data');
?>
<tr>
	<?php if($_dataHelper->getStoreConfig("onestepcheckout/general/allowremoveproduct")):?>
		<td class="a-center"><a href="javascript:void(0);" title="<?php echo __('Remove item')?>" class="btn-remove2 btn-checkout-remove2" data-item-id="<?php echo $block->getItem()->getId()?>"></a></td>
	<?php endif; ?>

	<?php if($_dataHelper->showImageProduct()):?>
        <?php $img_size = $_dataHelper->getStoreConfig('onestepcheckout/addfield/img_product_size');
            if(!$img_size) {
                $img_size = '128x128';
            }
            $product_size = explode('x',$img_size);
            $img_width = $product_size[0];
            $img_height = $product_size[1];
            $box_width = ($img_width+20).'px';
            $box_height = ($img_height+20).'px';
            $_product = $_item->getProduct();
            $productImageUrl = $this->helper('Magento\Catalog\Helper\Image')
                ->init($_product, 'category_page_list')
                ->constrainOnly(false)
                ->keepAspectRatio(false)
                ->keepFrame(false)
                ->resize($img_width, $img_height)
                ->getUrl();
        ?>
		<td class="ost-item-image" style=""><?php if ($block->hasProductUrl()):?><a href="<?php echo $block->getProductUrl() ?>" title="<?php echo $block->escapeHtml($block->getProductName()) ?>"><?php endif;?><img src="<?php echo $productImageUrl; ?>" width="<?php echo $img_width ?>" height="<?php echo $img_height ?>" style="max-width: none" alt="<?php echo $block->escapeHtml($block->getProductName()) ?>" /><?php if ($block->hasProductUrl()):?></a><?php endif;?></td>
	<?php endif; ?>

    <td class="col item" data-th="<?php echo $block->escapeHtml(__('Product Name'));?>"><strong class="product name product-item-name"><?php echo $block->escapeHtml($block->getProductName()) ?></strong>
        <?php if ($_options = $block->getOptionList()):?>
        <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
            <dd>
                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                    <?php echo $_formatedOptionValue['full_view'] ?>
                <?php else: ?>
                    <?php echo $_formatedOptionValue['value'] ?>
                <?php endif; ?>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif;?>
        <?php if ($addtInfoBlock = $block->getProductAdditionalInformationBlock()):?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif;?>
    </td>
    <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price'));?>">
        <?php if ($_taxHelper->displayCartPriceInclTax() || $_taxHelper->displayCartBothPrices()): ?>
            <span class="price-including-tax" data-label="<?php echo $block->escapeHtml(__('Incl. Tax'));?>">
                <?php echo $block->getUnitPriceInclTaxHtml($_item); ?>
            </span>
        <?php endif; ?>
        <?php if ($_taxHelper->displayCartPriceExclTax() || $_taxHelper->displayCartBothPrices()): ?>
            <span class="price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Excl. Tax'));?>">
                <?php echo $block->getUnitPriceExclTaxHtml($_item); ?>
            </span>
        <?php endif; ?>
    </td>
    <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty'));?>">
        <?php if($_dataHelper->getStoreConfig("onestepcheckout/general/updateqtyproduct")):?>
            <input maxlength="12" class="input-text qty" title="<?php echo __('Qty')?>" size="4" value="<?php echo $_item->getQty() ?>" name="cart[<?php echo $block->getItem()->getId()?>][qty]">
        <?php else : ?>
            <span class="qty"><?php echo $_item->getQty() ?></span>
        <?php endif; ?>
    </td>
    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal'));?>">
        <?php if ($_taxHelper->displayCartPriceInclTax() || $_taxHelper->displayCartBothPrices()): ?>
            <span class="price-including-tax" data-label="<?php echo $block->escapeHtml(__('Incl. Tax'));?>">
                <?php echo $block->getRowTotalInclTaxHtml($_item); ?>
            </span>
        <?php endif; ?>
        <?php if ($_taxHelper->displayCartPriceExclTax() || $_taxHelper->displayCartBothPrices()): ?>
            <span class="price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Excl. Tax'));?>">
                <?php echo $block->getRowTotalExclTaxHtml($_item); ?>
            </span>
        <?php endif; ?>
    </td>
</tr>
