<?php	
	/**		
		* Copyright © 2015 Magento. All rights reserved.		
		* See COPYING.txt for license details.		
	*/	
		
	// @codingStandardsIgnoreFile	
		
?>
<?php	
	/**		
		* Product list toolbar		
		*		
		* @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar		
	*/	
	use Magento\Catalog\Model\Product\ProductList\Toolbar;	
?>
<?php if ($block->getCollection()->getSize()): ?>
<div class="toolbar toolbar-products" data-mage-init='<?php /* @escapeNotVerified */ echo $block->getWidgetOptionsJson(); ?>'>	
		
    <?php 		
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();		
		$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category		
		/*echo $category->getId();			
		echo $category->getName();*/		
	?>	
	<?php echo $block->getPagerHtml() ?>	
	<?php if($category):?><div class="manualcategorytitle">		    	<h1 class="page-title">			        	<span class="base"> <?php echo $category->getManualTitle()?$category->getManualTitle():$category->getName();?></span>    					</h1>			</div>	
	<?php endif; ?>
	<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>	
	<?php if ($block->isExpanded()): ?>	
	<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>	
	<?php endif; ?>	
			
</div>
<?php endif ?>
