<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2016] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Cart2Quote
 * @package     Desk
 * @copyright   Copyright (c) 2016 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var Cart2Quote\Desk\Block\Adminhtml\Edit\Container\Create $block */
?>

<div class="create-message-container" data-mage-init='{"createMessage":{}}'>
    <header>
        <div class="conversation-title">
            <span>
                <input form="edit_form"
                       type="text"
                       name="subject"
                       placeholder="<?php echo __("Enter your subject") ?>"
                       value="<?php echo $this->getSubject() ?>"/>
            </span>
        </div>
    </header>
    <div class="create-message">
        <div class="set-conversation-type">
            <ul>
                <li class="public-reply active"><?php echo __("Public reply") ?></li>
                <li class="internal-note"><?php echo __("Internal note") ?></li>
            </ul>
        </div>
        <div class="textarea-container">
            <textarea form="edit_form" name="message" placeholder="<?php echo __("Enter your message") ?>"></textarea>
        </div>
        <input form="edit_form"
               id="is-private-message"
               style="display: none;"
               type="checkbox"
               name="is_private"
               value="1">
    </div>
</div>