<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2016] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Cart2Quote
 * @package     Desk
 * @copyright   Copyright (c) 2016 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var Cart2Quote\Desk\Block\Adminhtml\Edit\Container\Messages $block */
?>

<div class="message-container"
     data-last-id="<?php echo $block->getLastId()?>"
     data-ticket-id="<?php echo $block->getTicketId()?>"
     data-mage-init='{"ajaxUpdateContent":{"url": "<?php echo $block->getAjaxUpdateMessagesUrl()?>"}}'>
<?php foreach($block->getMessages() as $key => $message): ?>
    <?php echo $block->getChildBlock('ticket.edit.container.messages.message')
        ->setKey($key)->setMessage($message)->toHtml()?>
    <?php
endforeach;
?>
</div>
