<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2016] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Cart2Quote
 * @package     Desk
 * @copyright   Copyright (c) 2016 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var Cart2Quote\Desk\Block\Magento\Contact\Success $block */
?>

<div class="actions-toolbar">
    <div class="primary">
        <button type="button"
                onclick="window.location.replace('<?php echo $block->getUrl('desk/customer/new') ?>')"
                title="<?php /* @escapeNotVerified */ echo __("New Ticket") ?>"
                class="action primary add customer-add-ticket">
            <span>
                <?php /* @escapeNotVerified */ echo __("New Ticket") ?>
            </span>
        </button>
    </div>
</div>