<div class="menu-custom-block">
    <div class="home-block">
        <a class="home-link" href="/"> Home </a>
        <a class="close-btn" href="javascript:void(0);" data-action="toggle-nav">close</a>
    </div>
	<?php /*
    <div class="mobile-call-section">
        <a class="mobile-call" href="tel:1 (855) 552-2623"> 1 (855) 552-2623 </a>
    </div>
	
    <div class="mobile-search">
        <div class="search-wrapper">
            <div class="search-content block block-search" id="search-content"><a class="search-icon" title="Search"
                                                                                  href="javascript:void(0);"><span>Search</span></a>

                <div class="search-form-container">
                    <form class="form minisearch" id="search_mini_form"
                          action="/catalogsearch/result/" method="get">
                        <div class="field search"><label class="label" for="search" data-role="minisearch-label"><span>Search</span></label>

                            <div class="control"><input id="search" type="text" name="q" value=""
                                                        placeholder="Search..." class="input-text" maxlength="128"
                                                        role="combobox" aria-haspopup="false" aria-autocomplete="both"
                                                        autocomplete="off">

                                <div id="search_autocomplete" class="search-autocomplete"></div>
                            </div>
                        </div>
                        <div class="actions">
                            <button type="submit" title="Search" class="action search primary"><span>Search</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
	*/ ?>
    <div class="clearboth">&nbsp;</div>
</div>