<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div id="api-gateway-prompt-modal" style="margin: 3%;display: none;">
    <p>You are about to start connecting your Magento store catalog with Amazon.</p>
    <p>To continue, you must create an API security key in your Magento.com account and add it to your Amazon Sales Channel configuration in your Magento Admin.</p>
    <br/>
    <p style="font-weight: bold;">Get API Key</p>
    <p>1. <a href="<?= $block->getApiPortalUrl() ?>" target="_blank">Sign in</a> to your Magento account and get the API Key.</p>
    <br/>
    <p style="font-weight: bold;">Add Key</p>
    <p>2. <a href="<?= $block->getApiKeyConfigPageUrl() ?>">Add the key</a> to your store configuration in Amazon Sales Channel API</p>
    <br/>
    <p><a href="<?= $block->getApiKeyFaqUrl() ?>" target="_blank">User Guide</a></p>
</div>

<script type="text/javascript">
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function (
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                title: '<img style="height: 2em;vertical-align:middle;margin-left: 3%;" src = "<?=$block->getViewFileUrl(
    'Magento_Amazon::images/Amazon-Logo-Transparent-PNG.png'
)
                    ?>"> Welcome to Amazon Sales Channel',
                buttons: [],
                clickableOverlay: false,
                keyEventHandlers: {
                    // disable close on ESC
                    escapeKey: function () {
                        return;
                    }
                }
            };

            <?php if (!$block->isValidApiGatewayKey()): ?>
                modal(options, $("#api-gateway-prompt-modal"));
                $('#api-gateway-prompt-modal').modal('openModal');
                $('.action-close').css("visibility", "hidden"); // hide X button
                $('div.menu-wrapper').css('z-index', '10000'); // make admin menu usable
            <?php else: ?>
                $('#api-gateway-prompt-modal').hide();
            <?php endif; ?>
        }
    );
</script>