<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="dashboard-container row">
    <?= $block->getChildHtml('amazon_view_logs') ?>
    <?php if (is_array($block->getChildBlock('amazon_view_logs')->getTabsIds())) : ?>
        <div id="amazon_view_logs_tab_content" class="amazon-view-logs-tab-content"></div>
    <?php endif; ?>
</div>
