<?php
/**
 * Cart2Quote
 */

/** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */
/** @var $_quote \Cart2Quote\Quotation\Model\Quote */
?>
<?php $parentItem = $block->getItem() ?>
<?php $items = array_merge([$parentItem], $parentItem->getChildren()); ?>
<?php $_count = count($items) ?>
<?php $_index = 0 ?>
<?php $_item = $block->getItem() ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($items as $_item): ?>
    <?php $_quote = $_item->getQuote() ?>
    <?php if ($_item->getOptions() || $parentItem->getDescription()): ?>
        <?php $_showlastRow = true ?>
    <?php else: ?>
        <?php $_showlastRow = false ?>
    <?php endif; ?>

    <?php if ($_item->getParentItem()): ?>
        <tr class="options-label">
            <?php $attributes = unserialize($_item->getOptionByCode('bundle_selection_attributes')->getValue()); ?>
            <td class="col label" colspan="2" style="padding: 2px 20px; font-weight: bold; font-style: italic;"><?php echo $attributes['option_label']; ?></td>
        </tr>
    <?php endif; ?>
    <tr id="order-item-row-<?php echo $_item->getItemId() ?>" class="<?php if ($_item->getParentItem()): ?>item-options-container<?php else: ?>item-parent<?php endif; ?>"<?php if ($_item->getParentItem()): ?> data-th="<?php echo $_item->getName() ?>"<?php endif; ?>>
        <?php if (!$_item->getParentItem()): ?>
            <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
                <strong class="product name product-item-name"><?php echo $_item->getName() ?></strong>
                <p class="product-description"><?php echo $block->escapeHtml($_item->getProduct()->getResource()->getAttributeRawValue($_item->getProduct()->getEntityId(),'quote_description',0)) ?></p>
                <p class="sku"><?php echo  __('SKU'); ?>: <?php echo $block->escapeHtml($_item->getSku()) ?></p>
            </td>
        <?php else: ?>
            <td class="col value" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>" style="padding: 2px 20px;">
                <?php echo $block->escapeHtml($_item->getQty() . ' x ' . $_item->getName()) ?>
                <span class="price">
                    &nbsp;<?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_item->getPrice() * $_item->getQty(),true,false) ?>
                </span>
            </td>
        <?php endif; ?>
        <?php if (!$_item->getParentItem()): ?>
            <td>
                <?php echo $_item->getQty(); ?>
            </td>
        <?php endif; ?>
        <?php if (!$_item->getParentItem()): ?>
            <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>" style="padding: 10px;">
                <?php if(!$_item->getProduct()->getResource()->getAttributeRawValue($_item->getProduct()->getEntityId(),'quote_hide_price',$_item->getStoreId())):?>
                    <?php echo $block->getItemRowTotalHtml(); ?>
                <?php else: ?>
                    --
                <?php endif;?>
            </td>
        <?php endif; ?>
    </tr>
    <?php if ($_item->getDescription()) : ?>
        <tr>
            <td class="item-comment">
                <div class="item-comment-container" style="padding-left:20px;">
                    <p class="product-name">Comment</p>
                    <?php echo $_item->getDescription(); ?>
                </div>
            </td>
            <td colspan="1"></td>
        </tr>
    <?php endif; ?>
<?php endforeach; ?>


