<?php
use Cart2Quote\Quotation\Block\Quote\Email\Items\Bundle as B; /** @var B $block */ $b = $block; /** @var B $b */
use Magento\Catalog\Model\Product as P;
/** @var $_quote \Cart2Quote\Quotation\Model\Quote */
$parentItem = $b->getItem();
$items = array_merge([$parentItem], $parentItem->getChildren());
$_count = count($items);
$_index = 0;
$_item = $b->getItem();
$_prevOptionId = '';
foreach ($items as $_item):
	$p = $_item->getProduct(); /** @var P $p */
	$_quote = $_item->getQuote() ?>
    <?php if ($_item->getOptions() || $parentItem->getDescription()): ?>
        <?php $_showlastRow = true ?>
    <?php else: ?>
        <?php $_showlastRow = false ?>
    <?php endif; ?>

    <?php if ($_item->getParentItem()): ?>
        <tr class="options-label">
            <?php
				# 2021-04-02 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
				# 1) "`Cart2Quote_Quotation`: «unserialize(): Error at offset 0 of 61 bytes» in
				# `app/design/frontend/MageSuper/magestylish/Cart2Quote_Quotation/templates/email/quote/items/quote/bundle.phtml:22`":
				# https://github.com/canadasatellite-ca/site/issues/67
				# 2) "`bundle_selection_attributes` should be decoded using `json_decode` instead of `unserialize`":
				# https://github.com/canadasatellite-ca/site/issues/68
				$attributes = df_json_decode($_item->getOptionByCode('bundle_selection_attributes')->getValue());
			?>
            <td class="col label" colspan="2" style="padding: 2px 20px; font-weight: bold; font-style: italic;"><?php echo $attributes['option_label']; ?></td>
        </tr>
    <?php endif; ?>
    <tr id="order-item-row-<?php echo $_item->getItemId() ?>" class="<?php if ($_item->getParentItem()): ?>item-options-container<?php else: ?>item-parent<?php endif; ?>"<?php if ($_item->getParentItem()): ?> data-th="<?php echo $_item->getName() ?>"<?php endif; ?>>
        <?php if (!$_item->getParentItem()): ?>
            <td class="col name" data-th="<?php echo $b->escapeHtml(__('Product Name')); ?>">
                <strong class="product name product-item-name"><?php echo $_item->getName() ?></strong>
<?php
	# 2021-03-31 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
	# "`Cart2Quote_Quotation`: «Array to string conversion»
	# in `app/design/frontend/MageSuper/magestylish/Cart2Quote_Quotation/templates/email/quote/items/quote/bundle.phtml:35`":
	# https://github.com/canadasatellite-ca/site/issues/63
	echo cs_quote_description($p);
?>
                <p class="sku"><?php echo  __('SKU'); ?>: <?php echo $b->escapeHtml($_item->getSku()) ?></p>
            </td>
        <?php else: ?>
            <td class="col value" data-th="<?php echo $b->escapeHtml(__('Product Name')); ?>" style="padding: 2px 20px;">
                <?php echo $b->escapeHtml($_item->getQty() . ' x ' . $_item->getName()) ?>
                <span class="price">
                    &nbsp;<?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_item->getPrice() * $_item->getQty(),true,false) ?>
                </span>
            </td>
        <?php endif; ?>
        <?php if (!$_item->getParentItem()): ?>
            <td>
                <?php echo $_item->getQty(); ?>
            </td>
        <?php endif; ?>
        <?php if (!$_item->getParentItem()): ?>
            <td class="col subtotal" data-th="<?php echo $b->escapeHtml(__('Subtotal')); ?>" style="padding: 10px;">
                <?php if(!$_item->getProduct()->getResource()->getAttributeRawValue($_item->getProduct()->getEntityId(),'quote_hide_price',$_item->getStoreId())):?>
                    <?php echo $b->getItemRowTotalHtml(); ?>
                <?php else: ?>
                    --
                <?php endif;?>
            </td>
        <?php endif; ?>
    </tr>
    <?php if ($_item->getDescription()) : ?>
        <tr>
            <td class="item-comment">
                <div class="item-comment-container" style="padding-left:20px;">
                    <p class="product-name">Comment</p>
                    <?php echo $_item->getDescription(); ?>
                </div>
            </td>
            <td colspan="1"></td>
        </tr>
    <?php endif; ?>
<?php endforeach; ?>