<?php
/**
 * Cart2Quote
 */

/** @var $block \Cart2Quote\Quotation\Block\Quote\Email\Items\DefaultItems */

/** @var $_item \Magento\Quote\Model\Quote\Item */
/** @var $_quote \Cart2Quote\Quotation\Model\Quote */
$_item = $block->getItem();
$_quote = $_item->getQuote();
?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()) : ?> has-extra<?php endif; ?>">
        <p class="product-name"><?php echo  $block->escapeHtml($_item->getName()) ?></p>
        <p class="product-description"><?php echo $block->escapeHtml($_item->getProduct()->getResource()->getAttributeRawValue($_item->getProduct()->getEntityId(),'quote_description',0)) ?></p>

        <p class="sku"><?php echo  __('SKU'); ?>: <?php echo  $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()) : ?>
            <dl class="item-options">
                <?php foreach ($block->getItemOptions() as $option) : ?>
                    <dt><strong><em><?php echo  $option['label'] ?></em></strong></dt>
                    <dd>
                        <?php echo  nl2br($option['value']) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) : ?>
            <?php echo  $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
    </td>
    <td class="item-qty"><?php echo  $_item->getQty() * 1 ?></td>
    <td class="item-price">
        <?php
        if (!$_item->getProduct()->getResource()->getAttributeRawValue($_item->getProduct()->getEntityId(),'quote_hide_price',$_item->getStoreId())):
        $price = $_item->getCurrentTierItem()->getCustomPrice();
        if ($price == null) {
            $price = $_item->getCurrentTierItem()->getOriginalPrice();
        }
        ?>
        <?php $_quote->formatPrice($price); ?>
        <?php else :?>
            --
        <?php endif; ?>
    </td>
</tr>

<?php if (!$block->isProductRemarkDisabled()) : ?>
    <?php if ($_item->getDescription()) : ?>
        <tr>
            <td class="item-comment" colspan="2">
                <div class="item-comment-container" style="padding-left:20px;">
                    <p class="product-name">Comment</p>
                    <?php echo $_item->getDescription(); ?>
                </div>
            </td>
        </tr>
    <?php endif; ?>
<?php endif; ?>

<?php
$_giftMessageHelper = $this->helper('Magento\GiftMessage\Helper\Message');
if ($_item->getGiftMessageId() && $_giftMessage = $_giftMessageHelper->getGiftMessage($_item->getGiftMessageId())) : ?>
    <tr>
        <td colspan="2" class="item-extra">
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?php echo  __('Gift Message') ?></h3>
                        <strong><?php echo  __('From:'); ?></strong> <?php echo  $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br/><strong><?php echo  __('To:'); ?></strong> <?php echo  $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br/><strong><?php echo  __('Message:'); ?></strong>
                        <br/><?php echo  $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
<?php endif; ?>
