<?php
/**
 * Copyright (c) 2020. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 * @codingStandardsIgnoreFile
 */

/** @var \Cart2Quote\Quotation\Block\Product\View $block */
$product = $block->getProduct();
$validators = json_encode($block->getQuantityValidators());

/**
 * If a product is saleable `$block->getChildHtml('', true)` is called from
 * Magento_Catalog::view/frontend/templates/product/view/addtocart.phtml
 * and it will echo our button block if not we have to add the qty box and echo the child html
 */
?>
<?php $quoteButton = $block->addChild('quote_button', 'Cart2Quote\Quotation\Block\Button'); ?>
<?php $_product = $block->getProduct(); ?>
<?php $cartButtonTitle = __('Add to Cart'); ?>
<?php $quoteButtonTitle = __('Add to Quote'); ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Cart2Quote_Quotation/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';
            var addToQuote = false;
            // $(window).load(function() {
            $('body').on('click', '#product-addtoquote-button', function (e) {
                addToQuote = "<?php echo $block->getUrl('quotation/quote/add')?>";
            });

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).quotationAddToCart({
                        quoteFormUrl: addToQuote,
                        bindSubmit: false,
                        noAjax: false
                    });

                    widget.quotationAddToCart('submitForm', $(form));
                    addToQuote = false;
                    return false;
                }
            });
            // })
        });
    </script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Cart2Quote_Quotation/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';
            var addToQuote = false;
            // $(window).load(function() {
            $('body').on('click', '#product-addtoquote-button', function (e) {
                addToQuote = "<?php echo $block->getUrl('quotation/quote/add') ?>";
                console.log($('#product_addtocart_form').attr('action'))
            });

            $('#product_addtocart_form').validation({
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).quotationAddToCart({
                        quoteFormUrl: addToQuote,
                        bindSubmit: false
                    });

                    widget.quotationAddToCart('submitForm', $(form));
                    addToQuote = false;
                    return false;
                }
            });
            // })
        });
    </script>
<?php endif; ?>
<?php if (!$product->isSaleable() && $block->showButton()) : ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) : ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php echo $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               maxlength="12"
                               value="<?php echo $block->escapeHtml($block->getProductDefaultQty() * 1) ?>"
                               title="<?php echo $block->escapeHtml(__('Qty')) ?>" class="input-text qty"
                               data-validate="<?php echo $block->escapeHtml($validators) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <?php echo $block->getChildBlock('addtoquote.button.container')->getChildHtml('addtoquote.button') ?>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php elseif ($block->getParentBlock() && $block->getChildBlock('addtoquote.button.container')) : ?>
        <?php if ($quoteButton->showQuoteButton() && !$quoteButton->showMessageNotLoggedIn()) : ?>
            <!-- Quote button start -->
            <button type="submit"
                    title="<?php echo $quoteButtonTitle ?>"
                    class="action tocart"
                    id="product-addtoquote-button">
                <span><?php echo $quoteButtonTitle ?></span>
            </button>
            <!-- Quote button stop -->
        <?php elseif ($quoteButton->showMessageNotLoggedIn()) : ?>
            <button id="product-addtoquote-button" disabled="disabled" class="action tocart">
                <span><?php echo __('Please login to add to Quote.'); ?></span>
            </button>
        <?php endif; ?>

        <?php echo $block->getChildHtml('', true) ?>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {
                "catalogAddToCart": {
                    "addToCartButtonSelector": "#product-addtocart-button",
                    "addToQuoteButtonSelector": "#product-addtoquote-button",
                    "printQuoteSelector": "#product-printquote-button",
                    "addToQuoteFormAction": "<?php echo $block->escapeHtml($block->getUrl('quotation/quote/add')) ?>",
                    "printQuoteAction": "<?php echo $block->escapeHtml($block->getUrl('quotation/quote/printpdf')) ?>"
                }
            }
        },
        "[data-role=swatch-options]": {
            "Magento_Swatches/js/swatch-renderer": {
                "selectorAddToCart": "#product-addtocart-button",
                "selectorAddToQuote": "#product-addtoquote-button"
            }
        }
    }
</script>
