<?php
/** @var \Mageplaza\AutoRelated\Block\Product\ProductList\ProductList $block */
$items = $block->getProductCollection();
?>
<?php
if ($items->getSize()) :
    $ruleId = $this->getRuleId();
    ?>
    <div class="mageplaza-autorelated-block block widget block-products-list">
        <?php if ($title = $block->getTitleBlock()): ?>
            <div class="mageplaza-autorelated-title block-title title">
                <h2 id="block-mageplaza-autorelated-heading-" .<?php echo $ruleId; ?>><?php /* @escapeNotVerified */ echo $title; ?></h2>
            </div>
        <?php endif; ?>
        <div class="block-content content" aria-labelledby="block-mageplaza-autorelated-heading">
            <div class="products wrapper <?php echo $block->getLayoutSlider() ? 'mageplaza-autorelated-slider' : 'grid products-grid'; ?> products-mageplaza-autorelated">
                <ol class="products list items product-items equalheight"
                    id="<?php echo $block->getLayoutSlider() ? 'mageplaza-autorelated-slider-' . $ruleId : 'mageplaza-autorelated-grid-' . $ruleId; ?>"
                    data-rule-id="<?php echo $ruleId; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ if ($iterator++ == 1) : ?>
                            <li class="item product product-item">
                        <?php else: ?>
                            </li><li class="item product product-item">
                        <?php endif; ?>

                        <?php echo $block->showItem($_item) ?>

                        <?php echo ($iterator == count($items) + 1) ? '</li>' : '' ?>
                        <?php endforeach; ?>
                </ol>
            </div>
        </div>
    </div>
<?php endif; ?>
