<dl class="items methods-payment" id="checkout-payment-method-load">
<?php
    $methods = $block->getMethods();
    $oneMethod = count($methods) <= 1;
?>
<?php if (empty($methods)): ?>
    <dt class="item-title">
        <?php echo __('No Payment Methods') ?>
    </dt>
<?php else:
    foreach ($methods as $_method):
        $_code = $_method->getCode();
?>
    <dt class="item-title <?php echo $_code ?>">
    <?php if (!$oneMethod): ?>
        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $block->escapeHtml($_method->getTitle()) ?>" <?php if ($block->getSelectedMethodCode() == $_code): ?> checked="checked"<?php endif; ?> class="radio payment_method_handle" />
    <?php else: ?>
        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio no-display payment_method_handle" />
        <?php $oneMethod = $_code; ?>
    <?php endif; ?>
        <label for="p_method_<?php echo $_code ?>"><?php echo $block->escapeHtml($block->getMethodTitle($_method)) ?> <?php echo $block->getMethodLabelAfterHtml($_method) ?></label>
    </dt>

    <?php if ($_code == 'authorizenet_directpost' || $_code == 'payflowpro') : ?>
        <dd class="item-content <?php echo $_code ?>">
            <?php
                echo $block->getLayout()->createBlock('Magento\Payment\Block\Form\Cc')
                    ->setMethod($_method)
                    ->toHtml();
            ?>
        </dd>
        <iframe name="authorize-iframe" id="authorize-iframe" width="400px" height="300px" style="display: none"></iframe>
    <?php else : ?>
        <?php if ($html = $block->getPaymentMethodFormHtml($_method)): ?>
            <dd class="item-content <?php echo $_code ?>">
                <?php echo $html; ?>
            </dd>
        <?php endif; ?>
    <?php endif; ?>
<?php endforeach;
    endif;
?>
</dl>
<div class="no-display" data-checkout-price="<?php echo (float)$block->getQuote()->getBaseGrandTotal(); ?>"></div>
<?php echo $block->getChildChildHtml('additional'); ?>