<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($order = $block->loadOrderInterface()): ?>
    <div>
        <div>
            <div class="entry-edit form-inline">
                <div class="section-config active">
                    <fieldset style="display:none" class="admin__collapsible-block" id="account_order_details_header">
                    </fieldset>
                    <fieldset class="admin__collapsible-block">
                        <table width="100%" border="0" style="border-collapse:separate; border-spacing:10px">
                            <tbody>
                                <tr>
                                    <td width="220px" align="right"><?= $block->escapeHtml(__('Order Number:')) ?></td>
                                    <?php if ($orderId = $order->getOrderId()): ?>
                                        <?php if ($salesOrderId = $order->getSalesOrderId()): ?>
                                            <?php $url = $block->getUrl('sales/order/view', ['order_id' => $salesOrderId]) ?>
                                            <td><a href="<?= $block->escapeHtml($url) ?>" target="_blank"><?= $block->escapeHtml($orderId) ?></a></td>
                                        <?php else: ?>
                                            <td><?= $block->escapeHtml($orderId) ?></td>
                                        <?php endif ?>
                                    <?php endif ?>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Status:')) ?></td>
                                    <td><?= $block->escapeHtml((($order->getStatus()) ? $order->getStatus() : 'N/A')) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Notes:')) ?></td>
                                    <td><?= $block->escapeHtml($order->getNotes()) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Buyer Email:')) ?></td>
                                    <td><?= $block->escapeHtml((($order->getBuyerEmail()) ? $order->getBuyerEmail() : 'N/A')) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Buyer Name:')) ?></td>
                                    <td><?= $block->escapeHtml((($order->getBuyerName()) ? $order->getBuyerName() : 'N/A')) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Currency:')) ?></td>
                                    <td><?= $block->escapeHtml($order->getCurrency()) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Order Total:')) ?></td>
                                    <td><?= $block->escapeHtml($order->getTotal()) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Inventory Reserved:')) ?></td>
                                    <td><?= $block->escapeHtml(__(($order->getReserved()) ? 'Yes' : 'No')) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Is Premium:')) ?></td>
                                    <td><?= $block->escapeHtml(__(($order->getIsPremium()) ? 'Yes' : 'No')) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Is Prime:')) ?></td>
                                    <td><?= $block->escapeHtml(__(($order->getIsPrime()) ? 'Yes' : 'No')) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Purchase Date:')) ?></td>
                                    <?php $date = strtotime($order->getPurchaseDate()) ?>
                                    <td><?= $block->escapeHtml(date('m/d/Y H:i:s', $date)) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Latest Ship Date:')) ?></td>
                                    <?php $date = strtotime($order->getLatestShipDate()) ?>
                                    <td><?= $block->escapeHtml(date('m/d/Y H:i:s', $date)) ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </fieldset>
                    <fieldset class="admin__collapsible-block">
                        <table width="100%" border="0" style="border-collapse:separate; border-spacing:10px">
                            <tbody>
                                <tr>
                                    <td width="220px" align="right"><?= $block->escapeHtml(__('Shipping Service:')) ?></td>
                                    <td><?= $block->escapeHtml((($order->getShipServiceLevel()) ? $order->getShipServiceLevel() : 'N/A')) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Shipping Service Level:')) ?></td>
                                    <td><?= $block->escapeHtml((($order->getServiceLevel()) ? $order->getShipServiceLevel() : 'N/A')) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Shipped By Amazon:')) ?></td>
                                    <td><?= $block->escapeHtml(__(($order->getShippedByAmazon()) ? 'Yes' : 'No')) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Is Business:')) ?></td>
                                    <td><?= $block->escapeHtml(__(($order->getIsBusiness()) ? 'Yes' : 'No')) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Items Shipped:')) ?></td>
                                    <td><?= $block->escapeHtml($order->getItemsShipped()) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Items Unshipped:')) ?></td>
                                    <td><?= $block->escapeHtml($order->getItemsUnshipped()) ?></td>
                                </tr>
                                <tr>
                                    <td align="right"><?= $block->escapeHtml(__('Fulfillment Channel:')) ?></td>
                                    <td><?= $block->escapeHtml($order->getFulfillmentChannel()) ?></td>
                                </tr>
                                <tr>
                                    <td valign="top" align="right"><?= $block->escapeHtml(__('Shipping Address:')) ?></td>
                                    <td>
                                        <?php if ($name = $order->getShipName()): ?>
                                            <?= $block->escapeHtml($name) ?><br>
                                        <?php endif ?>
                                        <?php if ($address = $order->getShipAddressOne()): ?>
                                            <?= $block->escapeHtml($address) ?><br>
                                        <?php endif ?>
                                        <?php if ($address = $order->getShipAddressTwo()): ?>
                                            <?= $block->escapeHtml($address) ?><br>
                                        <?php endif ?>
                                        <?php if ($address = $order->getShipAddressThree()): ?>
                                            <?= $block->escapeHtml($address) ?><br>
                                        <?php endif ?>
                                        <?php if ($city = $order->getShipCity()): ?>
                                            <?= $block->escapeHtml($city) . ', ' ?>
                                        <?php endif ?>
                                        <?php if ($region = $order->getShipRegion()): ?>
                                            <?= $block->escapeHtml($region) . '  ' ?>
                                        <?php endif ?>
                                        <?php if ($postalCode = $order->getShipPostalCode()): ?>
                                            <?= $block->escapeHtml($postalCode) ?><br>
                                        <?php endif ?>
                                        <?php if ($country = $order->getShipCountry()): ?>
                                            <?= $block->escapeHtml($country) ?><br>
                                        <?php endif ?>
                                        <?php if ($phone = $order->getShipPhone()): ?>
                                            <?= $block->escapeHtml($phone) ?>
                                        <?php endif ?>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>
<?php endif ?>
