<?php
use Mageplaza\AutoRelated\Model\Config\Source\Additional;
/** @var \Mageplaza\AutoRelated\Block\Product\ProductList\ProductList $block */
$_item = $block->getProduct();
?>

<div class="product-item-info-slick">
    <?php /* @escapeNotVerified */ echo '<!-- recently_viewed_products_grid_content_widget-->' ?>
    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
        <?php echo $block->getImage($_item, 'recently_viewed_products_grid_content_widget')->toHtml(); ?>
    </a>
    <div class="product details product-item-details">
        <strong class="product name product-item-name">
            <a class="product-item-link"
               title="<?php echo $block->escapeHtml($_item->getName()) ?>"
               href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                <?php echo $block->escapeHtml($_item->getName()) ?>
            </a>
        </strong>

        <?php if ($block->getShowList(Additional::SHOW_REVIEW)) : ?>
            <?php echo $block->getReviewsSummaryHtml($_item, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW, true) ?>
        <?php endif; ?>

        <?php if ($block->getShowList(Additional::SHOW_PRICE)): ?>
            <?php echo $block->getProductPrice($_item); ?>
        <?php endif; ?>

        <?php
        $showCart          = $block->getShowList(Additional::SHOW_CART);
        $showAddtoWishlist = $block->getShowList(Additional::SHOW_WISHLIST);
        $showAddtoCompare  = $block->getShowList(Additional::SHOW_COMPARE);

        if ($showCart || $showAddtoWishlist || $showAddtoCompare): ?>
            <div class="product actions product-item-actions">
                <?php if ($showCart): ?>
                    <div class="actions-primary">
                        <?php if ($_item->isSaleable()): ?>
                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                <button class="action tocart primary mageplaza-autorelated-button"
                                        data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                </button>
                            <?php else: ?>
                                <?php
                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                $postData       = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                ?>
                                <button class="action tocart primary mageplaza-autorelated-button"
                                        data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                </button>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php if ($_item->getIsSalable()): ?>
                                <div class="stock available">
                                    <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                            <?php else: ?>
                                <div class="stock unavailable">
                                    <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
                <?php if ($showAddtoWishlist || $showAddtoCompare): ?>
                    <div class="secondary-addto-links actions-secondary"
                         data-role="add-to-links">
                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showAddtoWishlist): ?>
                            <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                               class="action towishlist" data-action="add-to-wishlist"
                               title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                            </a>
                        <?php endif; ?>
                        <?php if ($block->getAddToCompareUrl() && $showAddtoCompare): ?>
                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                            <a href="#" class="action tocompare"
                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>'
                               data-role="add-to-links"
                               title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
                                <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                            </a>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
</div>