<?php
use Interactivated\Quotecheckout\Block\Checkout\Onepage\Shipping\Sortshipping as B;
/** @var B $block */ $b = $block; /** @var B $b */
$_dataHelper = $this->helper('MW\Onestepcheckout\Helper\Data');
$_dob = $b->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob');
$_gender = $b->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender');
$_taxvat = $b->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat');

$name = '';
$company = '';
$email = '';
$street = '';
$city = '';
$state = '';
$zipcode = '';
$country = '';
$telephone = '';
$fax = '';
$name = $b->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
	->setTemplate('Interactivated_Quotecheckout::customer/widget/name.phtml')
	->setObject($b->getAddress())
	->setFieldIdFormat('shipping:%s')
	->setFieldNameFormat('shipping[%s]')
	->toHtml();

$company = '<div class="field">
		<label for="shipping:company" class=""><em>' . $b->isStar('company') . '</em>' . __('Company') . '</label>
		<div class="input-box">
			<input type="text" id="shipping:company" name="shipping[company]" value="' . $b->escapeHtml($b->getAddress()->getCompany()) . '" title="' . __('Company') . '" class="input-text inputtext ' . $b->isRequired('company') . '" />
		</div>
	</div>';

$streetValues = $b->getAddress()->getStreet();
$val_street_1 = $streetValues[0];
if ($val_street_1 == 'n/a') {
	$val_street_1 = '';
}
$street = '<div>
	<ul>
		<li class="wide">
			<label for="shipping:street1" class=""><em>' . $b->isStar('street') . '</em>' . __('Address') . '</label>
			<div class="input-box">
				<input type="text" title="' . __('Street Address') . '" name="shipping[street][]" id="shipping:street1" value="' . $b->escapeHtml($val_street_1) . '" class="input-text inputtext  ' . $b->isRequired('street') . '" />
			</div>
		</li>';
for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++) {
	if (isset($streetValues[$_i - 1])) {
		$temp_address = $streetValues[$_i - 1];
		if($temp_address =='n/a') {
			$temp_address = '';
		}
	} else {
		$temp_address = '';
	}

	$street = $street . '<li class="wide">
							<div class="input-box">
								<input type="text" title="' . __('Street Address %1', $_i) . '" name="shipping[street][]" id="shipping:street' . $_i . '" value="' . $b->escapeHtml($temp_address) . '" class="input-text inputtext" />
							</div>
						</li>';
}
$street = $street . '</ul></div>';

$vat_id = '';
$_addressHelper = $this->helper('Magento\Customer\Helper\Address');
if ($_addressHelper->isVatAttributeVisible()){
	$vat_id = '
	<li class="wide" id="osc_shipping_vat_id">
		<label for="shipping:vat_id">'.__('VAT Number').'</label>
		<div class="input-box">
			<input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="'.$b->escapeHtml($b->getAddress()->getVatId()).'" title="'.__('VAT Number').'" class="input-text '.$_addressHelper->getAttributeValidationClass('vat_id').'" />
		</div>
	</li>
	';
}

$cityval = $b->getAddress()->getCity();
$city = '<div class="field">
		<label for="shipping:city" class=""><em>' . $b->isStar('city') . '</em>' . __('City') . '</label>
		<div class="input-box">
			<input type="text" title="' . __('City') . '" name="shipping[city]" value="' . $b->escapeHtml($cityval) . '" class="input-text inputtext  ' . $b->isRequired('city') . '" id="shipping:city" />
		</div>
	</div>';


$region = $b->getAddress()->getRegion();
$regionidval = (isset($region['region_id'])) ? $region['region_id'] : '';
$regionval = (isset($region['region'])) ? $region['region'] : '';
$state = '<div class="field">
		<label for="shipping:region_id" class=""><em>' . $b->isStar('state') . '</em>' . __('Province / State') . '</label>
		<div class="input-box shipping_region_class">
			<select id="shipping:region_id"  name="shipping[region_id]" title="' . __('Province / State') . '" ' . (($_dataHelper->getStoreConfig("onestepcheckout/addfield/state") == 1) ? 'class="validate-select shipping_region_clas "' : ' ') . ' style="display:none;">
				<option value="">' . __('Please select region, state or province') . '</option>
			</select>

			<script type="text/javascript">
				require([
					"jquery"
				], function($) {
					//<![CDATA[
						$("#shipping:region_id").attr("defaultValue",  "' . $regionidval . '");
					//]]>
				});
			</script>

			<input type="text" id="shipping:region" name="shipping[region]" value="' . $b->escapeHtml($regionval) . '"  title="' . __('Province / State') . '" class="input-text inputtext  ' . $b->isRequired('state') . '" style="display:none;" />
		</div>
	</div>';

$postcodeval = $b->getAddress()->getPostcode();
$zipcode = '<div class="field">
		<label for="shipping:postcode" class=""><em>' . $b->isStar('zip') . '</em>' . __('Postal / ZIP Code') . '</label>
		<div class="input-box">
			<input type="text" title="' . __('Zip/Postal Code') . '" name="shipping[postcode]" id="shipping:postcode" value="' . $b->escapeHtml($postcodeval) . '" class="input-text inputtext validate-zip-international  ' . $b->isRequired('zip') . '" />
		</div>
	</div>';

$country = '<div class="field" ' . (($_dataHelper->getStoreConfig("onestepcheckout/addfield/country") == 0) ? "style=\"display:none\"" : "") . '>
		<label for="shipping:country_id" class=""><em>' . $b->isStar('country') . '</em>' . __('Country') . '</label>
		<div class="input-box">
			' . $b->getCountryHtmlSelect('shipping') . '
		</div>
	</div>';

$telephone = '<div class="field">
		<label for="shipping:telephone" class=""><em>' . $b->isStar('telephone') . '</em>' . __('Phone') . '</label>
		<div class="input-box">
			<input type="text" name="shipping[telephone]" value="' . $b->escapeHtml($b->getAddress()->getTelephone()) . '" title="' . __('Phone') . '" class="input-text inputtext  ' . $b->isRequired('telephone') . '" id="shipping:telephone" />
		</div>
	</div>';

$fax = '<div class="field">
		<label for="shipping:fax" class=""><em>' . $b->isStar('fax') . '</em>' . __('Fax') . '</label>
		<div class="input-box">
			<input type="text" name="shipping[fax]" value="' . $b->escapeHtml($b->getAddress()->getFax()) . '" title="' . __('Fax') . '" class="input-text inputtext  ' . $b->isRequired('fax') . '" id="shipping:fax" />
		</div>
	</div>';

$type_address = ['company', 'street', 'city', 'state', 'zip', 'country', 'telephone', 'fax', 'vat_id', 'name'];

$shippingBlock = ["", "", "", "", "", "", "", "","",""];
$temp = [];
$notdisable = [];
$filter = [];
foreach ($type_address as $nametype) {
	if (!$b->isDisable($nametype)) {
		$notdisable[] = $nametype;
	}
}
foreach ($notdisable as $namevalid) {
	if ($namevalid == 'vat_id') {
		$filter[] = $_dataHelper->getStoreConfig('onestepcheckout/options_sort/sort_city') + 1;
	} else {
		$filter[] = $_dataHelper->getStoreConfig('onestepcheckout/options_sort/sort_' . $namevalid);
	}
}
for ($i = 0; $i < count($filter); $i++) {
	for ($j = $i + 1; $j < count($filter); $j++) {
		if ($filter[$i] == $filter[$j]) {
			$temp[] = $filter[$i];
			break;
		}
	}
}
$temp[] = $_dataHelper->getStoreConfig('onestepcheckout/options_sort/sort_name');

$nameinputs = [
	'name'=> $name,
	'company' => $company,
	'street' => $street,
	'city' => $city,
	'state' => $state,
	'zip' => $zipcode,
	'country' => $country,
	'telephone' => $telephone,
	'fax' => $fax,
	'vat_id' =>  $vat_id
];
foreach ($nameinputs as $nameadd => $bitem) {
	if (!in_array($nameadd, $notdisable)) {
		// If input is disable in configuration
		continue;
	}

	if (!in_array($_dataHelper->getStoreConfig('onestepcheckout/options_sort/sort_' . $nameadd), $temp)) {
		$res = '';
		if(isset($shippingBlock[$_dataHelper->getStoreConfig('onestepcheckout/options_sort/sort_' . $nameadd)])){
			$res = $shippingBlock[$_dataHelper->getStoreConfig('onestepcheckout/options_sort/sort_' . $nameadd)];
		}
		$shippingBlock[$_dataHelper->getStoreConfig('onestepcheckout/options_sort/sort_' . $nameadd)] = '<div class="widthfull">' . $res . $bitem . '</div>';
	}else if($nameadd == 'vat_id'){
		$shippingBlock[1] = $bitem;
	} else {
		$shippingBlock[$_dataHelper->getStoreConfig('onestepcheckout/options_sort/sort_' . $nameadd)] = $shippingBlock[$_dataHelper->getStoreConfig('onestepcheckout/options_sort/sort_' . $nameadd)] . $bitem;
	}
}

$str = '';// '<li>' . $name . '</li>';
foreach ($shippingBlock as $bitem) {
	if ($bitem == "") {
		continue;
	}

	$str = $str . '<div class="clear"></div><li class="fields">' . $bitem . '</li>';
}
if (!$_dataHelper->getStoreConfig("onestepcheckout/addfield/country")) {
	$str = $str . '<div class="clear"></div><li class="fields">' . $country . '</li>';
}

if ($b->isDisable('state')) {
	$str = $str . '<div style="display:none;"><select id="shipping:region_id" name="shipping[region_id]"></select>
	<input type="text" id="shipping:region" name="shipping[region]"  style="display:none;" /></div>
	';
}
echo $str;
?>

<script type="text/x-magento-init">
	{
		"#shipping\\:country_id": {
			"regionUpdater": {
				"optionalRegionAllowed": <?php echo($b->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
				"regionListId": "#shipping\\:region_id",
				"regionInputId": "#shipping\\:region",
				"postcodeId": "#shipping\\:postcode",
				"regionJson": <?php echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
				"defaultRegion": "<?php echo $b->getAddress()->getRegionId() ?>",
				"countriesWithOptionalZip": <?php echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
			}
		}
	}
</script>
