<?php
use Interactivated\Quotecheckout\Block\Checkout\Onepage\Billing as B;
/** @var B $block */ $b = $block; /** @var B $b */
	$_dataHelper = $this->helper('MW\Onestepcheckout\Helper\Data');
	$_persistentSession = $this->helper('Magento\Persistent\Helper\Session');

	$registerParam = $b->getRequest()->getParam('register');
	if ($registerParam || $registerParam === '') :
?>
	<script type="text/javascript">
		require([
			'jquery'
		], function($) {
			//<![CDATA[
				$(document).ready(function() {
					if ($('#login:register')) {
						$('#login:register').checked = true;
						checkout.setMethod();
					}
				});
			//]]>
		});
	</script>
<?php endif; ?>

<div id="co-billing-form">
	<ul class="form-list">
		<?php if ($b->customerHasAddresses() && $_dataHelper->showAddressBook()): ?>
			<li class="wide">
				<label for="billing-address-select"><?php echo __('Select a shipping address from your address book or enter a new address.') ?></label>
				<div class="input-box">
					<?php echo $b->getAddressesHtmlSelect('billing') ?>
				</div>
			</li>
		<?php endif; ?>

		<li id="billing-new-address-form">
			<input type="hidden" name="billing[address_id]" value="<?php echo $b->getAddress()->getId() ?>" id="billing:address_id" />

			<ul>
				<div id="mw_onstepcheckout_billing_form">
					<?php echo $b->getChildHtml('sortbilling');?>
				</div>
				<div style="clear:both;margin-top:5px;"></div>
				<?php
					if ($b->isCustomerLoggedIn()) :
				?>
					<li class="control">
						<input type="checkbox" style="z-index: 99" name="billing[save_in_address_book]" value="0" title="<?php echo __('Save in address book') ?>" id="billing:save_in_address_book" <?php if ($b->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
						<label for="billing:save_in_address_book"><?php echo __('Save in address book') ?></label>
					</li>

					<?php if(df_cfg('onestepcheckout/general/save_into_account')): ?>
						<li>
							<input type="checkbox" name="billing[save_into_account]" value="0" title="<?php echo __('Save as account information') ?>" id="billing:save_into_account"  class="checkbox" />
							<label for="billing:save_into_account"><?php echo __('Update account information') ?></label>
						</li>
					<?php endif; ?>
				<?php else :?>
					<li class="no-display">
						<input type="hidden" name="billing[save_in_address_book]" value="1" />
					</li>
				<?php endif; ?>
			</ul>
		</li>

		<li style="margin-top:-7px; clear: both">
			<?php if (df_cfg('onestepcheckout/general/allowshippingotheraddress')) : ?>
				<?php if (!$_dataHelper->onlyProductDownloadable()) : ?>
					<input type="checkbox" name="ship_to_same_address"  value="1" title="<?php echo __('ship to same address') ?>" id="ship_to_same_address" class="checkbox" checked="checked"> <label for="ship_to_same_address" style="float:none;"><?php echo __('Ship to same address') ?></label>
				<?php else: ?>
					<input type="hidden" name="ship_to_same_address"  value="1" title="<?php echo __('ship to same address') ?>">
				<?php endif; ?>
			<?php else: ?>
				<input type="hidden" name="ship_to_same_address"  value="1" title="<?php echo __('ship to same address') ?>">
			<?php endif; ?>
		</li>
	</ul>
</div>
