<?php
    $_dataHelper = $this->helper('Interactivated\Quotecheckout\Helper\Data');
?>
<div class="mw-osc-block-content mw-ost-review-ct">
	<div id="checkout-review-load">
		<?php  echo $block->getChildHtml('info') ?>
	</div>

	<?php if($_dataHelper->showCouponCode()) : ?>
        <div id="tab-coupon">
            <?php echo $block->getChildHtml('coupon');?>
        </div>
        <!-- for affiliate -->
        <?php if ($this->helper('Magento\Catalog\Helper\Data')->isModuleOutputEnabled('MW_Affiliate')) : ?>
        <div class="cart mwrw-discount">
            <div id="discount-referral-form">
                <?php echo $block->getChildHtml('referral_code_osc'); ?>
            </div>
        </div>
        <?php endif; ?>
	<?php endif; ?>
</div>

<?php if ($_dataHelper->showEditCartLink()) : ?>
	<p id="edit-cart" class="a-right" style="margin: 0px;"><?php echo __('Forgot an Item?') ?>
	<a href="<?php echo $block->getUrl('quotation/quote') ?>"><?php echo __('Edit Your Quote') ?></a>
	</p>
<?php endif; ?>

<div id="checkout-review-options">
	<?php echo $block->getChildHtml('options') ?>			
</div>		

<div id="checkout-review-submit">
	<div class="buttons-set" id="review-buttons-container">
        <!--  Subscribe Enable & Checked-->
        <div class="os-clear"></div>
        <div class="clear"></div>
        <div class="os-subcribe-newsletter">
            <?php if ($_dataHelper->getStoreConfig('onestepcheckout/addfield/allowsubscribenewsletter') == 1) : ?>
                <?php if($_dataHelper->isSubscribed()):?>
                    <input type="checkbox" name="subscribe_newsletter" value="0" title="<?php echo __('Subscribe newsletter') ?>" id="subscribe_newsletter" class="checkbox"> <label for="subscribe_newsletter" style="float:none;"><?php echo __('Subscribe newsletter') ?></label>
                <?php endif; ?>
            <?php endif; ?>

            <?php if ($_dataHelper->getStoreConfig('onestepcheckout/addfield/allowsubscribenewsletter') == 2) : ?>
                <?php if($_dataHelper->isSubscribed()):?>
                    <input type="checkbox" name="subscribe_newsletter" value="1" checked="checked" title="<?php echo __('Subscribe newsletter') ?>" id="subscribe_newsletter" class="checkbox"> <label for="subscribe_newsletter" style="float:none;"><?php echo __('Subscribe newsletter') ?></label>
                <?php endif; ?>
            <?php endif; ?>

        </div>

        <!--term and conditions-->
		<?php if ($_dataHelper->getStoreConfig('onestepcheckout/termcondition/allow_options')) : ?>
            <div class="onestepcheckout-enable-terms">
                <input class="required-entry" type="checkbox" id="id_accept_terms" name="accept_terms" value="1" />
				<label for="id_accept_terms"><em style="color:red;">* </em><?php echo __('I accept the');?> <a id="onestepcheckout-toc-link" target="_blank" href="#inline2"><?php echo __('Terms and Conditions');?></a></label>
    		</div>
		<?php endif; ?>

        <div class="clear"></div>
        <!-- check out button-->
		<div id="onestepcheckout_place_order_button">
			<button type="button" title="<?php echo __('Request Quote') ?>" class="button btn-checkout">
                <span id="onestepcheckout_place_btn_id">
                    <?php echo __('Request Quote') ?>
                </span>
            </button>
		</div>

		<span class="please-wait" id="review-please-wait" style="display:none;">
			<img src="<?php echo $block->getViewFileUrl('Interactivated_Quotecheckout::images/opc-ajax-loader.gif') ?>" alt="<?php echo __('Submitting quote information...') ?>" title="<?php echo __('Submitting quote information...') ?>" class="v-middle" /> <?php echo __('Submitting quote information...') ?>
		</span>
	</div>
</div>

<div id="checkout-paypaliframe-load" class="authentication"></div>