<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="general-info">
    <div class="help-and-general-form">
        <?= $block->escapeHtml(__('Provides the ability to select the proper Amazon listing from possible child listings')) ?>
    </div>
    <div class="help-button">
        <button type="button"
                class="action-default"
                onclick="window.open('<?= $block->getUserGuideUrl() . $block->getListingUpdateFormUrl() ?>', '_blank')"
                id="helpButton" >
            <span><?= $block->escapeHtml(__('View User Guide')) ?></span>
        </button>
    </div>
</div>

<?php if ($productInterface = $block->loadProductInterface()): ?>
    <?php $parentAsin = $block->getParentAsin() ?>
    <table width="100%" border="0" style="border-collapse:separate; border-spacing:10px; padding-bottom:40px">
        <tbody>
            <tr>
                <td width="220px" align="right"><?= $block->escapeHtml(__('SKU:')) ?></td>
                <?php if ($productId = $productInterface->getId()): ?>
                    <?php $url = $block->getUrl('catalog/product/edit', ['id' => $productId]) ?>
                    <td><a href="<?= $block->escapeHtml($url) ?>" target="_blank"><?= $block->escapeHtml($productInterface->getSku()) ?></a></td>
                <?php else: ?>
                    <td><?= $block->escapeHtml(__('N/A')) ?></td>
                <?php endif ?>
            </tr>
            <tr>
                <td align="right"><?= $block->escapeHtml(__('Product Name:')) ?></td>
                <td><?= $block->escapeHtml((($productInterface->getName()) ? $productInterface->getName() : 'N/A')) ?></td>
            </tr>
            <tr>
                <td align="right"><?= $block->escapeHtml(__('Parent ASIN:')) ?></td>
                <?php if ($parentAsin): ?>
                    <td><a href="<?= $block->escapeHtml('https://www.amazon.com/exec/obidos/ASIN/' . $parentAsin) ?>" target="_blank"><?= $block->escapeHtml($parentAsin) ?></a></td>
                <?php else: ?>
                    <td><?= $block->escapeHtml($parentAsin) ?></td>
                <?php endif ?>
            </tr>
        </tbody>
    </table>
<?php endif ?>
