<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2016] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Cart2Quote
 * @package     Desk
 * @copyright   Copyright (c) 2016 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var Cart2Quote\Desk\Block\Customer\Ticket\View $block */
?>

<?php $ticket = $block->getTicketData() ?>
<div class="ticket-details">
    <span class="ticket-details-title special-title"><?php echo __("Ticket Details") ?></span>
    <div class="ticket-details-field">
        <span class="ticket-details-label"><?php echo __("Status") ?></span>
        <span class="ticket-details-value"><?php echo ucfirst($ticket->getStatus())?></span>
    </div>
    <div class="ticket-details-field">
        <span class="ticket-details-label"><?php echo __("Priority") ?></span>
        <span class="ticket-details-value"><?php echo ucfirst($ticket->getPriority())?></span>
    </div>
    <div class="ticket-details-field">
        <span class="ticket-details-label"><?php echo __("Created at") ?></span>
        <span class="ticket-details-value"><?php echo $block->getCreatedAt()?></span>
    </div>
    <div class="ticket-details-field">
        <span class="ticket-details-label"><?php echo __("Assigned to") ?></span>
        <span class="ticket-details-value"><?php echo ucfirst($block->getAssignedTo())?></span>
    </div>
</div>