<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2016] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Cart2Quote
 * @package     Desk
 * @copyright   Copyright (c) 2016 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var Cart2Quote\Desk\Block\Customer\Ticket\View\Message $block */
?>

<div class="message <?php echo $block->getTicketDetailClass($this->getKey()) ?>">
        <div class="title">
            <span class="message-name">
                <?php echo $block->escapeHtml($this->getMessage()->getName()) ?>
            </span>
            <div class="message-date">
                <time class="date">
                    <?php /* @escapeNotVerified */ echo $block->dateFormat($this->getMessage()->getUpdatedAt())?>
                </time>
                <time class="time">
                    <?php /* @escapeNotVerified */ echo $block->timeFormat($this->getMessage()->getUpdatedAt())?>
                </time>
            </div>
        </div>
    <div class="message-content">
        <?php echo nl2br($block->escapeHtml($this->getMessage()->getMessage())) ?>
    </div>
</div>
