<?php
/**
 * @project: CartImport
 * @author : LitExtension
 * @url    : http://litextension.com
 * @email  : litextension@gmail.com
 */
?>
<?php
$notice = $block->getNotice();
$entities = "";
foreach($notice['config']['import'] as $key => $value){
    if($value == true){
        $entities .= '<p> - '.ucfirst($key).'</p>';
    }
}
?>
<form action="" method="post" id="form-confirm">
    <input type="hidden" name="action" value="confirm">
    <div class="container">
        <h1><?php echo __("Source Cart"); ?></h1>
        <div class="form-group">
            <div class="label-field">
                <p><label><?php echo  __("Cart Type"); ?>:</label></p>
            </div>
            <div class="input-field">
                <p><?php echo $block->getCartTypeByValue($notice['config']['cart_type']); ?></p>
            </div>
        </div>
        <div class="form-group">
            <div class="label-field">
                <p><label><?php echo  __("Cart Url"); ?>:</label></p>
            </div>
            <div class="input-field">
                <p><?php echo $notice['config']['cart_url']; ?></p>
            </div>
        </div>
    </div>
    <?php if($notice['config']['config_support']['category_map']){ ?>
    <div class="container">
        <h1><?php echo __("Root Category"); ?></h1>
        <?php foreach($notice['config']['category_data'] as $cat_key => $cat_name){ ?>
        <div class="form-group">
            <div class="label-field mapping">
                <p><label><?php echo $cat_name; ?></label></p>
            </div>
            <div class="input-field">
                <p><?php if(isset($notice['config']['cats'][$cat_key])) echo $block->getCategoryNameById($notice['config']['cats'][$cat_key]); ?></p>
            </div>
        </div>
        <?php } ?>
    </div>
    <?php } ?>
    <?php if($notice['config']['config_support']['attribute_map']){ ?>
    <div class="container">
        <h1><?php echo __("Product Attribute Set"); ?></h1>
        <?php foreach($notice['config']['attribute_data'] as $attr_key => $attr_name){ ?>
        <div class="form-group">
            <div class="label-field mapping">
                <p><label><?php echo $attr_name; ?></label></p>
            </div>
            <div class="input-field">
                <p><?php if(isset($notice['config']['attributes'][$attr_key])) echo $block->getAttributeSetNameById($notice['config']['attributes'][$attr_key]); ?></p>
            </div>
        </div>
        <?php } ?>
    </div>
    <?php } ?>
    <?php if($notice['config']['config_support']['language_map']){ ?>
    <div class="container">
        <h1><?php echo __("Languages Mapping"); ?></h1>
        <?php foreach($notice['config']['languages_data'] as $lang_key => $lang_name){ ?>
        <div class="form-group">
            <div class="label-field mapping">
                <p><label><?php echo $lang_name; ?></label></p>
            </div>
            <div class="input-field">
                <p><?php if(isset($notice['config']['languages'][$lang_key])) echo $block->getStoreNameById($notice['config']['languages'][$lang_key]); ?></p>
            </div>
        </div>
        <?php } ?>
    </div>
    <?php } ?>
    <?php if($notice['config']['config_support']['currency_map']){ ?>
    <div class="container">
        <h1><?php echo __("Currencies Mapping"); ?></h1>
        <?php foreach($notice['config']['currencies_data'] as $cur_key => $cur_name){ ?>
        <div class="form-group">
            <div class="label-field mapping">
                <p><label><?php echo $cur_name; ?></label></p>
            </div>
            <div class="input-field">
                <p><?php if(isset($notice['config']['currencies'][$cur_key])) echo $block->getCurrencyNameByCode($notice['config']['currencies'][$cur_key]); ?></p>
            </div>
        </div>
        <?php } ?>
    </div>
    <?php } ?>
    <?php if($notice['config']['config_support']['order_status_map']){ ?>
    <div class="container">
        <h1><?php echo __("Orders Status Mapping"); ?></h1>
        <?php foreach($notice['config']['order_status_data'] as $ord_stt_key => $ord_stt_name){ ?>
        <div class="form-group">
            <div class="label-field mapping">
                <p><label><?php echo $ord_stt_name; ?></label></p>
            </div>
            <div class="input-field">
                <p><?php if(isset($notice['config']['order_status'][$ord_stt_key])) echo $block->getOrderStatusByValue($notice['config']['order_status'][$ord_stt_key]); ?></p>
            </div>
        </div>
        <?php } ?>
    </div>
    <?php } ?>
    <?php if($notice['config']['config_support']['country_map']){ ?>
    <div class="container">
        <h1><?php echo __("Countries Mapping"); ?></h1>
        <?php foreach($notice['config']['countries_data'] as $country_key => $country_name){ ?>
            <div class="form-group">
                <div class="label-field mapping">
                    <p><label><?php echo $country_name; ?></label></p>
                </div>
                <div class="input-field">
                    <p><?php if(isset($notice['config']['countries'][$country_key])) echo $block->getCountryNameById($notice['config']['countries'][$country_key]); ?></p>
                </div>
            </div>
        <?php } ?>
    </div>
    <?php } ?>
    <div class="container">
        <h1><?php echo __("Entities to Migrate"); ?></h1>
        <div class="form-group">
            <div class="input-field">
                <?php echo $entities; ?>
            </div>
        </div>
    </div>
    <div class="container">
        <h1><?php echo __("Additional Options"); ?></h1>
        <div class="form-group">
            <div class="input-field">
                <?php if($notice['config']['add_option']['clear_data']){?><p> - <?php echo __("Clear current data on Target Store before Migration"); ?></p><?php } ?>
                <?php if($notice['config']['add_option']['seo_url']){?><p> - <?php echo __("Migrate categories and products SEO URLs"); ?></p><?php } ?>
                <?php if($notice['config']['add_option']['img_des']){?><p> - <?php echo __("Transfer images in product descriptions to your site"); ?></p><?php } ?>
                <?php if($notice['config']['add_option']['pre_cus']){?><p> - <?php echo __("Preserve Customer IDs on Target Store"); ?></p><?php } ?>
                <?php if($notice['config']['add_option']['pre_ord']){?><p> - <?php echo __("Preserve Order IDs on Target Store"); ?></p><?php } ?>
                <?php if($notice['config']['add_option']['stock']){?><p> - <?php echo __("Ignore stock management for products with quantity = 0"); ?></p><?php } ?>
            </div>
        </div>
    </div>
    <div class="form-submit">
        <?php if($notice['config']['add_option']['clear_data']){?>
        <div id="warning-clear" class="form-warning"><?php echo __('Warning: all current data of entities selected will be cleared.'); ?></div>
        <?php } ?>
        <div id="form-confirm-loading" class="form-loading"><?php echo __('Connecting ... ')?></div>
        <div id="form-confirm-submit" class="button-submit">
            <a href="javascript:void(0)" class="lecaip-button"><?php echo __('Start Migration') ?></a>
        </div>
    </div>
    <div>
        <a id="form-confirm-back" href="javascript:void(0)">&laquo; <?php echo __('Back to previous Step') ?></a>
    </div>
</form>