<?php
/**
 * @project: CartImport
 * @author : LitExtension
 * @url    : http://litextension.com
 * @email  : litextension@gmail.com
 */
?>
<?php
$notice = $block->getNotice();
$entities = '';
foreach($notice['config']['import'] as $key => $value){
    if($value == true){
        $entities .= '<p> - '.ucfirst($key).'</p>';
    }
}
?>
<form action="" method="post" id="form-resume">
    <div id="resume-wrap">
        <input type="hidden" name="action" value="resume">
        <h1>Incompleted Last Migration</h1>
        <div>Due to some reason, your last migration hasn't been completed yet. Please check the blow information and resume if you wish.</div>
        <br />
        <div class="resume-title"><?php echo __("Source Cart Setup"); ?></div>
        <div class="form-group">
            <div class="resume-label">
                <span><label><?php echo __('Cart Type'); ?></label></span>
            </div>
            <div class="resume-value">
                <span><?php echo $block->getCartTypeByValue($notice['config']['cart_type']); ?></span>
            </div>
        </div>
        <div class="form-group">
            <div class="resume-label">
                <span><label><?php echo __('Cart Url'); ?></label></span>
            </div>
            <div class="resume-value">
                <span><?php echo $notice['config']['cart_url']; ?></span>
            </div>
        </div>
        <?php if($notice['config']['config_support']['category_map']){ ?>
        <div class="resume-title"><?php echo __("Root Category"); ?></div>
        <?php foreach($notice['config']['category_data'] as $cat_key => $cat_name){ ?>
        <div class="form-group">
            <div class="resume-label">
                <p><label><?php echo $cat_name; ?></label></p>
            </div>
            <div class="resume-char"></div>
            <div class="resume-value">
                <p><?php if(isset($notice['config']['cats'][$cat_key])) echo $block->getCategoryNameById($notice['config']['cats'][$cat_key]); ?></p>
            </div>
        </div>
        <?php }} ?>
        <?php if($notice['config']['config_support']['attribute_map']){ ?>
        <div class="resume-title"><?php echo __("Product Attribute Set"); ?></div>
        <?php foreach($notice['config']['attribute_data'] as $attr_key => $attr_name){ ?>
        <div class="form-group">
            <div class="resume-label">
                <p><label><?php echo $attr_name; ?></label></p>
            </div>
            <div class="resume-char"></div>
            <div class="resume-value">
                <p><?php if(isset($notice['config']['attributes'][$attr_key])) echo $block->getAttributeSetNameById($notice['config']['attributes'][$attr_key]); ?></p>
            </div>
        </div>
        <?php }} ?>
        <?php if($notice['config']['config_support']['language_map']){ ?>
        <div class="resume-title"><?php echo __("Languages Mapping"); ?></div>
        <?php foreach($notice['config']['languages_data'] as $lang_key => $lang_name){ ?>
        <div class="form-group">
            <div class="resume-label">
                <p><label><?php echo $lang_name; ?></label></p>
            </div>
            <div class="resume-char"></div>
            <div class="resume-value">
                <p><?php if(isset($notice['config']['languages'][$lang_key])) echo $block->getStoreNameById($notice['config']['languages'][$lang_key]); ?></p>
            </div>
        </div>
        <?php }} ?>
        <?php if($notice['config']['config_support']['currency_map']){ ?>
        <div class="resume-title"><?php echo __("Currencies Mapping"); ?></div>
        <?php foreach($notice['config']['currencies_data'] as $cur_key => $cur_name){ ?>
        <div class="form-group">
            <div class="resume-label">
                <p><label><?php echo $cur_name; ?></label></p>
            </div>
            <div class="resume-char"></div>
            <div class="resume-value">
                <p><?php if(isset($notice['config']['currencies'][$cur_key])) echo $block->getCurrencyNameByCode($notice['config']['currencies'][$cur_key]); ?></p>
            </div>
        </div>
        <?php }} ?>
        <?php if($notice['config']['config_support']['order_status_map']){ ?>
        <div class="resume-title"><?php echo __("Orders Status Mapping"); ?></div>
        <?php foreach($notice['config']['order_status_data'] as $ord_stt_key => $ord_stt_name){ ?>
        <div class="form-group">
            <div class="resume-label">
                <p><label><?php echo $ord_stt_name; ?></label></p>
            </div>
            <div class="resume-char"></div>
            <div class="resume-value">
                <p><?php if(isset($notice['config']['order_status'][$ord_stt_key])) echo $block->getOrderStatusByValue($notice['config']['order_status'][$ord_stt_key]); ?></p>
            </div>
        </div>
        <?php }} ?>
        <?php if($notice['config']['config_support']['country_map']){ ?>
            <h1><?php echo __("Countries Mapping"); ?></h1>
            <?php foreach($notice['config']['countries_data'] as $country_key => $country_name){ ?>
                <div class="form-group">
                    <div class="resume-label">
                        <p><label><?php echo $country_name; ?></label></p>
                    </div>
                    <div class="resume-char"></div>
                    <div class="resume-value">
                        <p><?php if(isset($notice['config']['countries'][$country_key])) echo $block->getCountryNameById($notice['config']['countries'][$country_key]); ?></p>
                    </div>
                </div>
            <?php } ?>
        <?php } ?>
        <div class="resume-title"><?php echo __("Entities to Migrate"); ?></div>
        <div class="form-group">
            <div class="resume-value">
                <?php echo $entities; ?>
            </div>
        </div>
        <div class="resume-title"><?php echo __("Additional Options"); ?></div>
        <div class="form-group">
            <div class="resume-value">
                <?php if($notice['config']['add_option']['clear_data']){?><p> - <?php echo __("Clear current data on Target Store before Migration"); ?></p><?php } ?>
                <?php if($notice['config']['add_option']['seo_url']){?><p> - <?php echo __("Migrate categories and products SEO URLs"); ?></p><?php } ?>
                <?php if($notice['config']['add_option']['img_des']){?><p> - <?php echo __("Transfer images in product descriptions to your site"); ?></p><?php } ?>
                <?php if($notice['config']['add_option']['pre_cus']){?><p> - <?php echo __("Preserve Customer IDs on Target Store"); ?></p><?php } ?>
                <?php if($notice['config']['add_option']['pre_ord']){?><p> - <?php echo __("Preserve Order IDs on Target Store"); ?></p><?php } ?>
                <?php if($notice['config']['add_option']['stock']){?><p> - <?php echo __("Ignore stock management for products with quantity = 0"); ?></p><?php } ?>
            </div>
        </div>
        <div class="resume-title"><?php echo __("Previous Process"); ?></div>
        <div class="form-group">
            <div class="resume-value">
                <?php
                foreach($notice['config']['import'] as $key => $value){
                    if($value == true){ ?>
                        <p> - <?php echo $notice[$key]['imported'].'/'.$notice[$key]['total'].' '.$key.' completed, '.$notice[$key]['error'].' errors' ?><?php if($notice[$key]['finish']){echo '<span class="success-icon" style="display: inline-block;margin-left: 0.5em;"></span>';}?></p>
                    <?php }
                }
                ?>
            </div>
        </div>
        <div class="resume-title"><?php echo __("Do you want to resume last migration?"); ?></div>
        <div class="form-submit">
            <div id="form-resume-loading" class="form-loading"><?php echo __('Connecting ... ')?></div>
            <div id="form-resume-submit" class="button-submit">
                <a href="javascript:void(0)" class="lecaip-button"><?php echo __('Resume') ?></a>
            </div>
        </div>
        <div style="clear: both;"></div>
    </div>
</form>