<?php
/**
 * Magedelight
 * Copyright (C) 2018 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2018 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php
// @codingStandardsIgnoreFile
/** @var \Magedelight\Subscribenow\Block\Catalog\Product\View\Subscription $block */
?>
<?php if ($block->canDisplaySubscription()): ?>
    <input type="hidden" name="productviewpage" value="yes" />
    <?php echo $block->getChildHtml('subscription.type'); ?>
    <div id="md_subscription_content" style="<?php echo ($block->canDisplayContent())?'':'display: none;';?>">
        <div class="product-options-wrapper">
            <div class="field">
                <h4><?php echo __('Subscription Details'); ?></h4>
                <?php echo $block->getChildHtml('billing.period'); ?>
                <label for="subscription_start" class="label">
                    <?php echo __('Subscription Start Date :'); ?>
                </label>
                <?php echo $block->getChildHtml('billing.date'); ?>
                <?php echo $block->getChildHtml('additional.info'); ?>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        require(["jquery"],
            function ($) {
                var subscriptioOption = 'input:radio[name="options[_1]"]'; 
                if($(subscriptioOption+':checked').val() === 'subscription') {
                    $('#md_subscription_content').show();
                }
                $(subscriptioOption).on('change', function(event){
                    if (event.originalEvent !== undefined) {
                        var subscriptionType = $(this).val();
                        
                        if(subscriptionType == "subscription"){
                            $('#md_subscription_content').show();
                        }else{
                            $('#md_subscription_content').hide();
                        }
                    }
                });
            }
        );
    </script>
<?php endif; ?>