<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Aheadworks\AdvancedReviews\Block\Base */
?>

<div data-role="aw-ar-email-subscriber-form" data-bind="scope: 'awArEmailSubscriberForm'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{

    "[data-role=aw-ar-email-subscriber-form]": {
        "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout() ?>
    }
}
</script>
