<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="help-button">
    <button type="button"
        class="action-default"
        onclick="window.open('<?= $block->getUserGuideUrl() . $block->getListingOverridesFormUrl() ?>', '_blank')"
        id="helpButton" >
        <span><?= $block->escapeHtml(__('View User Guide')) ?></span>
    </button>
</div>

