<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Magento\Amazon\Block\Adminhtml\Amazon\Account\ActionButtons $block */
?>
<?php $account = $block->getAccount() ?>

<?php $merchantId = $account->getMerchantId() ?>
<?php $arguments['merchant_id'] = ($merchantId) ?: '' ?>

<?php $current = (int)$block->getData('current') ?>
<?php $arguments['current'] = ($current) ?: 1 ?>

<div data-mage-init='{"floatingHeader": {}}' class="page-actions amazon-topbar-wrapper">
    <div class="amazon-topbar-leftCol">
        <div class="amazon-topbar-storeName">
            <span> Store Name: </span><?= $account->getName() ?>
        </div>
        <div class="amazon-topbar-website">
            <span class="boldLabel">Magento website: </span>
            <span><?= $block->getMagentoWebsite($account)->getName() ?></span>
        </div>
    </div>
    <div class="amazon-topbar-rightCol">
        <div class="action-wrap action-wrap-prev">
            <button type="button"
                    class="spectrumButton spectrumButton--secondary back"
                    onclick="window.location.href='<?= $block->escapeHtml($block->getBackButtonUrl()) ?>'"
                    id="backButton">
                <span><?= $block->escapeHtml(__('Back')) ?></span>
            </button>
        </div>

        <?php if ($block->isListingSettingsPage()): ?>
            <?php $url = $block->storeUrl()->listingSave($account) ?>
            <div class="action-wrap">
                <button id="save" type="button"
                        class="spectrumButton"
                        onclick="window.location.href='<?= $block->escapeHtml($url) ?>'">
                    <span><?= $block->escapeHtml(__('Save listing settings')) ?></span>
                </button>
            </div>
        <?php elseif ($block->isListingRulesPage()): ?>
            <?php $url = $block->storeUrl()->listingRulesPreview($account) ?>
            <div class="action-wrap">
                <button id="save" type="button"
                        class="spectrumButton"
                        onclick="window.location.href='<?= $block->escapeHtml($url) ?>'">
                    <span><?= $block->escapeHtml(__('Preview changes')) ?></span>
                </button>
            </div>
        <?php elseif ($block->isStorePreviewPage()): ?>
            <?php
            $url = $block->storeUrl()->listingRulesSave($account);
            ?>
            <div class="action-wrap">
                <button id="save" type="button"
                        class="spectrumButton"
                        onclick="window.location.href='<?= $block->escapeHtml($url) ?>'">
                    <span><?= $block->escapeHtml(__('Save and close')) ?></span>
                </button>
            </div>
        <?php elseif ($block->isOrderSettingsPage()): ?>
            <?php $url = $block->storeUrl()->settingsOrdersSave($account) ?>
            <div class="action-wrap">
                <button id="save" type="button"
                        class="spectrumButton"
                        onclick="window.location.href='<?= $block->escapeHtml($url) ?>'">
                    <span><?= $block->escapeHtml(__('Save order settings')) ?></span>
                </button>
            </div>
        <?php elseif ($block->isPricingRulesListPage()): ?>
            <?php $createRuleUrl = $block->storeUrl()->pricingRulesCreate($account) ?>
            <button type="button"
                    class="spectrumButton"
                    onclick="window.location.href='<?= $block->escapeHtml($createRuleUrl) ?>'">
                <span><?= $block->escapeHtml(__('Add new pricing rule')) ?></span>
            </button>
        <?php endif ?>
    </div>
</div>
