<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="general-info">
    <div class="help-and-general-form">
        <?= $block->escapeHtml(__('This step allows you to connect your Amazon store to your Magento store to create a single source for your catalog.')) ?>
    </div>
    <div class="help-button">
        <button type="button"
                class="action-default"
                onclick="window.open('<?= $block->getUserGuideUrl() . $block->getCredentialSettingsUrl() ?>', '_blank')"
                id="helpButton">
            <span><?= $block->escapeHtml(__('View User Guide')) ?></span>
        </button>
    </div>
</div>

<div id="marketplace-save-link" style="display:none" data-storeurl="<?= $block->escapeHtml($block->getUrl('*/*/account_settings_credentials_setup/')) ?>" />
<div id="marketplace-reload" style="display:none" data-storeurl="<?= $block->escapeHtml($block->getUrl('*/*/account_settings_credentials_index/')) ?>" />
