<?php /** @var $block \BroSolutions\CryptoCoins\Block\Widget\Crypto */ ?>
<?php
$title = $this->getTitle();
$ctaLink = $block->getCtaLink();
$ctaText = $block->getCtaText();
?>
<div class="crypto-coins-wrap">
    <?php if ($title): ?>
        <div class="crypto-coins-title"><?= $title ?></div>
    <?php endif; ?>
    <div class="crypto-coins-exchange"
         id="crypto-coins-exchange"
         data-mage-init='{
            "BroSolutions_CryptoCoins/js/crypto": {
                "interval": 2000,
                "url": "<?= $this->getUrl('cryptocurrency/crypto/index') ?>",
                "priceChangePercent": <?= $block->getPriceChangePercent() ?>,
                "priceChange": <?= $block->getPriceChange() ?>,
                "lowPriceChange": <?= $block->getLowPriceChange() ?>,
                "limit": <?= $block->getLimit() ?>,
                "imagePath": "<?= $block->getViewFileUrl('BroSolutions_CryptoCoins') ?>",
                "highPriceChange": <?= $block->getHighPriceChange() ?>
            }
         }'></div>
    <?php if ($ctaLink && $ctaText): ?>
        <a href="<?= $ctaLink ?>"><?= $ctaText ?></a>
    <?php endif; ?>
</div>
<style>
    .crypto-coins-title {
        padding: 0px;
        text-align: center;
        margin: 20px;
        font-size: 18px;
    }
    .more {
        box-sizing: border-box;
        margin: 0px;
        display: flex;
        -webkit-box-align: center;
        align-items: center;
        -webkit-box-pack: end;
        justify-content: flex-end;
        color: rgb(14, 203, 129);
    }
    .less {
        box-sizing: border-box;
        margin: 0px;
        display: flex;
        -webkit-box-align: center;
        align-items: center;
        -webkit-box-pack: end;
        justify-content: flex-end;
        color: rgb(246, 70, 93);
    }
    .crypto-coins-item {
        box-sizing: border-box;
        margin: 0;
        min-width: 0;
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        padding-top: 8px;
        padding-bottom: 8px;
        padding-left: 8px;
        padding-right: 8px;
        line-height: 1.3;
        border-radius: 4px;
        -webkit-align-items: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: justify;
        -webkit-justify-content: space-between;
        -ms-flex-pack: justify;
        justify-content: space-between;
        background-color: #fff;
        border-bottom: 1px solid rgb(242,242,242);
        font-size: 14px;
        font-weight: 400;
        color: #1E2329;
    }
    .pair {
        box-sizing: border-box;
        margin: 0;
        min-width: 0;
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        -webkit-flex-direction: column;
        -ms-flex-direction: column;
        flex-direction: column;
        margin-left: 16px;
    }
    th {
        box-sizing: border-box;
        margin: 0;
        min-width: 0;
        display: -webkit-box;
        word-break: break-word;
        -webkit-box-orient: vertical;
    }
    table {
        box-sizing: border-box;
        margin: 0;
        min-width: 0;
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        box-shadow: 0px 0px 20px rgba(0,0,0,0.08);
        border-radius: 0px;
        -webkit-flex-direction: column;
        -ms-flex-direction: column;
        flex-direction: column;
    }
    .crypto-coins-item-head {
        box-sizing: border-box;
        margin: 0;
        min-width: 0;
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        padding-top: 8px;
        padding-bottom: 8px;
        padding-left: 8px;
        padding-right: 8px;
        line-height: 1.3;
        border-radius: 4px;
        -webkit-align-items: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: justify;
        -webkit-justify-content: space-between;
        -ms-flex-pack: justify;
        justify-content: space-between;
        background-color: #fff;
        border-bottom: 1px solid rgb(242,242,242);
    }

    .crypto-coins-item-head strong {
        margin-left: 15px;
        font-weight: 300;
    }
    .crypto-coins-item-last-price {
        box-sizing: border-box;
        margin: 0;
        min-width: 0;
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        -webkit-align-items: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
    }
    .crypto-coins-item {
        box-sizing: border-box;
        margin: 0;
        min-width: 0;
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        padding-top: 8px;
        padding-bottom: 8px;
        padding-left: 8px;
        padding-right: 8px;
        line-height: 1.3;
        border-radius: 4px;
        -webkit-align-items: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: justify;
        -webkit-justify-content: space-between;
        -ms-flex-pack: justify;
        justify-content: space-between;
        background-color: #fff;
        border-bottom: 1px solid rgb(242,242,242);
        font-size: 14px;
        font-weight: 400;
        color: #1E2329;
    }
</style>
