<?php
$categoryId = $block->getRequest()->getParam('category_id');

$faqQuestions = $block->getQuestionCollection($categoryId);
$firstchaild = 1;
//print_r($block->LoadCategoryModel()->getData());
?>
<div class="faqs-cat-header">
    <h2 class="faqs-cat-title" style="color: <?php echo $block->LoadCategoryModel()->getBackground(); ?>">
        <?php  
            $icon = ($block->LoadCategoryModel()->getIcon()) ? $block->LoadCategoryModel()->getIcon() :'fa-folder-open';
        ?>
        <i class="fa <?php echo $icon; ?>" style="color: <?php echo $block->LoadCategoryModel()->getBackground(); ?>"></i>
        <?php echo $block->LoadCategoryModel()->getTitle(); ?>
    </h2>
    <div class="faqs-cat-image">
        <img src="<?php echo $block->LoadCategoryModel()->getImageUrl(); ?>" alt="<?php echo $block->LoadCategoryModel()->getTitle(); ?>">
    </div>
    <div class="faqs-cat-desc">
        <?php echo $block->LoadCategoryModel()->getDescription(); ?>
    </div>
</div>
<div class="main-faqs-page-index-view">
    <div class="panel-group question-list " id="accordion" >
        <?php foreach ($faqQuestions as $faqQuestion) { ?>
            <div class="panel panel-default">
                <?php $randomNumber = rand(999, 9999); ?>
                <div class="panel-heading faqcat-question collapsed"
                     data-toggle="collapse"
                     data-target="#collapse-<?php /* @noEscape */ echo $faqQuestion->getId() . $randomNumber; ?>"
                     data-parent="#accordion"
                     data-animated="<?php echo $block->LoadCategoryModel()->getAnimationType(); ?>"
                     data-color-active="<?php echo $block->LoadCategoryModel()->getTextColorActive(); ?>"
                     data-bg-color-active="<?php echo $block->LoadCategoryModel()->getBackgrondActive(); ?>"
                     data-color="<?php echo $block->LoadCategoryModel()->getTextColor(); ?>"
                     data-bg-color="<?php echo $block->LoadCategoryModel()->getBackground(); ?>"
                     style="background-color:<?php echo $block->LoadCategoryModel()->getBackground(); ?>; border-color: <?php echo $block->LoadCategoryModel()->getBorderWidth(); ?>; border-width:<?php echo $block->LoadCategoryModel()->getBorderColor(); ?>;border-radius: <?php echo $block->LoadCategoryModel()->getBorderRadius(); ?>; margin-bottom: <?php echo $block->LoadCategoryModel()->getQuestionMarginBottom(); ?>; "
                     >
                    <h4 class="panel-title">
                        <a class="accordion-toggle faq_questions_title" style="color:<?php echo $block->LoadCategoryModel()->getTextColor(); ?>" href="javascript:void(0);">
                        <?php  
                        $icon = ($block->LoadCategoryModel()->getIconClass()) ? $block->LoadCategoryModel()->getIconClass() :'fa-plus-square-o';
                        $iconActive = ($block->LoadCategoryModel()->getIconActive()) ? $block->LoadCategoryModel()->getIconActive() :'fa-minus-square-o';
                        ?>
                            <i data-icon="<?php echo $icon; ?>" data-icon-active="<?php echo $iconActive; ?>" class="main_icon fa <?php echo $icon; ?>"></i> 
                            <?php echo $block->escapeHtml($faqQuestion->getQuestion()); ?>
                        </a>
                    </h4>
                </div>
                <div id="collapse-<?php /* @noEscape */ echo $faqQuestion->getId() . $randomNumber; ?>" class="panel-collapse collapse animated">   
                    <div class="panel-body">
                        <?php echo $block->getAnswerContant($faqQuestion->getAnswer()); ?>...
                        <a style="color: #fc6b1f" href="<?php echo $block->getUrl('faqs/question/view/id/' . $faqQuestion->getId() . ''); ?>">Read more</a>
                    </div>
                </div>
            </div>

        <?php } ?>
    </div>
</div>
<div class="child_faqcategories">
<?php
$faqCategories = $block->getChildrenCategories($categoryId);
foreach($faqCategories as $faqCategory):
    $randomNumber = rand(999, 9999);
    $faqQuestions = $block->getQuestionCollection($faqCategory->getCategoryId());
    if(count($faqQuestions)): ?>
        <div class="child_category panel panel-default" id="categories_accordion">
            <div class="panel-heading faqcat-subcat "
                 data-toggle="collapse"
                 data-target="#collapse-<?php /* @noEscape */ echo $faqCategory->getCategoryId() . $randomNumber; ?>"
                 data-parent="#categories_accordion"
                 data-animated="<?php echo $block->LoadCategoryModel()->getAnimationType(); ?>"
                 data-color-active="<?php echo $block->LoadCategoryModel()->getTextColorActive(); ?>"
                 data-bg-color-active="<?php echo $block->LoadCategoryModel()->getBackgrondActive(); ?>"
                 data-color="<?php echo $block->LoadCategoryModel()->getTextColor(); ?>"
                 data-bg-color="<?php echo $block->LoadCategoryModel()->getBackground(); ?>"
                 aria-expanded="true"
                 style="background-color:<?php echo $block->LoadCategoryModel()->getBackground(); ?>; border-color: <?php echo $block->LoadCategoryModel()->getBorderWidth(); ?>; border-width:<?php echo $block->LoadCategoryModel()->getBorderColor(); ?>;border-radius: <?php echo $block->LoadCategoryModel()->getBorderRadius(); ?>; margin-bottom: <?php echo $block->LoadCategoryModel()->getQuestionMarginBottom(); ?>; "
            >
                <h4 class="panel-title">
                    <a class="accordion-toggle faq_subcategory_title" style="color:<?php echo $block->LoadCategoryModel()->getTextColor(); ?>" href="javascript:void(0);">
                        <?php
                        $icon = ($block->LoadCategoryModel()->getIconClass()) ? $block->LoadCategoryModel()->getIconClass() :'fa-plus-square-o';
                        $iconActive = ($block->LoadCategoryModel()->getIconActive()) ? $block->LoadCategoryModel()->getIconActive() :'fa-minus-square-o';
                        ?>
                        <i data-icon="<?php echo $icon; ?>" data-icon-active="<?php echo $iconActive; ?>" class="main_icon fa <?php echo $iconActive; ?>"></i>
                        <?php echo $block->escapeHtml($faqCategory->getTitle()); ?>
                    </a>
                </h4>
            </div>
            <div id="collapse-<?php /* @noEscape */ echo $faqCategory->getCategoryId() . $randomNumber; ?>" class="panel-collapse collapse animated questions in">
                <div class="main-faqs-page-index-view">
                    <div class="panel-group question-list " id="accordion" >
                        <?php foreach ($faqQuestions as $faqQuestion) { ?>
                            <div class="panel panel-default">
                                <?php $randomNumber = rand(999, 9999); ?>
                                <div class="panel-heading faqcat-question collapsed"
                                     data-toggle="collapse"
                                     data-target="#collapse-<?php /* @noEscape */ echo $faqQuestion->getId() . $randomNumber; ?>"
                                     data-parent="#accordion"
                                     data-animated="<?php echo $block->LoadCategoryModel()->getAnimationType(); ?>"
                                     data-color-active="<?php echo $block->LoadCategoryModel()->getTextColorActive(); ?>"
                                     data-bg-color-active="<?php echo $block->LoadCategoryModel()->getBackgrondActive(); ?>"
                                     data-color="<?php echo $block->LoadCategoryModel()->getTextColor(); ?>"
                                     data-bg-color="<?php echo $block->LoadCategoryModel()->getBackground(); ?>"
                                     style="background-color:<?php echo $block->LoadCategoryModel()->getBackground(); ?>; border-color: <?php echo $block->LoadCategoryModel()->getBorderWidth(); ?>; border-width:<?php echo $block->LoadCategoryModel()->getBorderColor(); ?>;border-radius: <?php echo $block->LoadCategoryModel()->getBorderRadius(); ?>; margin-bottom: <?php echo $block->LoadCategoryModel()->getQuestionMarginBottom(); ?>; "
                                >
                                    <h4 class="panel-title">
                                        <a class="accordion-toggle faq_questions_title" style="color:<?php echo $block->LoadCategoryModel()->getTextColor(); ?>" href="javascript:void(0);">
                                            <?php
                                            $icon = ($block->LoadCategoryModel()->getIconClass()) ? $block->LoadCategoryModel()->getIconClass() :'fa-plus-square-o';
                                            $iconActive = ($block->LoadCategoryModel()->getIconActive()) ? $block->LoadCategoryModel()->getIconActive() :'fa-minus-square-o';
                                            ?>
                                            <i data-icon="<?php echo $icon; ?>" data-icon-active="<?php echo $iconActive; ?>" class="main_icon fa <?php echo $icon; ?>"></i>
                                            <?php echo $block->escapeHtml($faqQuestion->getQuestion()); ?>
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapse-<?php /* @noEscape */ echo $faqQuestion->getId() . $randomNumber; ?>" class="panel-collapse collapse animated">
                                    <div class="panel-body">
                                        <?php echo $block->getAnswerContant($faqQuestion->getAnswer()); ?>...
                                        <a style="color: #fc6b1f" href="<?php echo $block->getUrl('faqs/question/view/id/' . $faqQuestion->getId() . ''); ?>">Read more</a>
                                    </div>
                                </div>
                            </div>

                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    <?php endif;?>
<?php endforeach;?>
</div>
<script>
    require(['jquery', 'jquery.bootstrap'], function ($) {
        $(document).ready(function () {
            $('.collapse').on('shown.bs.collapse', function (e) {
                var target = e.target;
                var $collapsebody = $(target).parent().find(".faqcat-question").first();
                var $icon = $(target).parent().find(".main_icon").first();
                var animated = $collapsebody.attr('data-animated');
                var colorActive = $collapsebody.attr('data-color-active');
                var bgColorActive = $collapsebody.attr('data-bg-color-active');
                var dataIcon = $icon.attr('data-icon');
                var dataIconActive = $icon.attr('data-icon-active');
                
                $(target).addClass(animated);
                $icon.removeClass(dataIcon).addClass(dataIconActive);
                $collapsebody.css("background-color", bgColorActive);
                $(target).parent().find(".faq_questions_title").first().css("color", colorActive);
                $(target).closest('.question-list').find('.collapse').not(target).collapse('hide');

            }).on('hidden.bs.collapse', function (e) {
                var target = e.target;
                var $collapsebody = $(target).parent().find(".faqcat-question").first();
                var $icon = $(target).parent().find(".main_icon").first();
                var color = $collapsebody.attr('data-color');
                var bgColor = $collapsebody.attr('data-bg-color');
                var dataIcon = $icon.attr('data-icon');
                var dataIconActive = $icon.attr('data-icon-active');
                $icon.removeClass(dataIconActive).addClass(dataIcon);
                $collapsebody.css("background-color", bgColor);
                $(target).parent().find(".faq_questions_title").first().css("color", color);
            });
        });
    });
</script>