<?php
$_dataHelper = $this->helper('Interactivated\Quotecheckout\Helper\Data');
?>
<div class="shipping-option">
	<div class="mw-osc-block-title">
		<p class="onestepcheckout-numbers onestepcheckout-numbers-3" id='mw-osc-p3'>
			<?php echo __('Delivery Time');?>
		</p>		
	</div>
    
	<div class="mw-osc-block-content">
        <div id="delivery_date_load">
            <ul>
                <?php if($_dataHelper->getStoreConfig('onestepcheckout/deliverydate/asa_option')) : ?>
                    <li style="margin-bottom:10px;">
                        <label>
                            <input type="radio" name="deliverydate" value="now" checked="checked" style="margin-right:5px;"><span><?php echo __('As soon as possible');?></span>
                        </label>
                    </li>
                <?php endif; ?>
                <li>
                    <label style="margin-right:5px;">
                        <?php if($_dataHelper->getStoreConfig('onestepcheckout/deliverydate/asa_option')) : ?>
                            <input type="radio" name="deliverydate" value="late" style="margin-right:5px;">
                        <?php else : ?>
                            <input type="hidden" name="deliverydate" value="late">
                        <?php endif; ?>
                        <span><?php echo __('Select preferred time');?></span>
                    </label>

                    <div id="deliveryshow">
                        <div id="datex">
                            <div class="blockdate">
                                <span><?php echo __('Date:');?> </span>

    							<span id="date" style="text-align:left;">
    								<?php $mytime = date('h:i a', $_dataHelper->getDateTime()->timestamp(time())); ?>
    							</span>
                            </div>
                            <input type="hidden" name="onestepcheckout_date" id="onestepcheckout_date" value=""/>
                            <input type="hidden" name="onestepcheckout_offset" id="onestepcheckout_offset" value=""/>
                        </div>

                        <div id="timex">
                            <div id="changedate">
                                <div class="blockdate">
                                    <span><?php echo __('Time:');?> </span>
                                    <span id="clock"><?php echo $mytime ?></span>
                                </div>
                                <input type="hidden" name="onestepcheckout_time" id="onestepcheckout_time" value="<?php echo $mytime ?>"/>
                            </div>
                            <?php
                                if ($_dataHelper->getStoreConfig('onestepcheckout/deliverydate/timerange')) :
                                    $time = $_dataHelper->getStoreConfig('onestepcheckout/deliverydate/addtimerange');
                                    if ($time) {
                                        $arraytime = unserialize($time);
                                        $slotime = [];
                                        foreach ($arraytime as $time => $timerange) {
                                            $slotime[] = implode("-", $timerange);
                                        }
                                    }
                            ?>
                                <div class="mwost-deltime">
                                    <select id="delivery-timerange" size="1" name="delivery-timerange">
                                        <option value=""><?php echo __('Time Range');?></option>
                                        <?php foreach ($slotime as $slot) : ?>
                                            <?php if ($slot) : ?>
                                                <option value="<?php echo $slot ?>"><?php echo $slot ?></option>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            <?php endif; ?>
                        </div>

                        <div style="clear:both;"></div>
                    </div>
                </li>
            </ul>
        </div>
	</div>
</div>