<?php
/**
 * Cart2Quote
 */

?>
<?php $_quote = $block->getQuote() ?>
<?php if ($_quote) : ?>
    <?php $_items = $_quote->getAllItems(); ?>
    <table class="email-items">
        <thead>
        <tr>
            <th class="item-info">
                <?= __('Items'); ?>
            </th>
            <th class="item-qty">
                <?= __('Qty'); ?>
            </th>
            <th class="item-price">
                <?= __('Price'); ?>
            </th>
        </tr>
        </thead>
        <?php foreach ($_items as $_item) : ?>
            <?php
            if ($_item->getParentItem()) {
                continue;
            }
            ?>
            <tbody>
            <?php echo $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot class="order-totals">
        <?= $block->getChildHtml('quote_totals') ?>
        </tfoot>
    </table>
    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('quote', $_quote,
            $_quote->getStore()) && $_quote->getGiftMessageId()
    ) : ?>
        <?php
        $_giftMessageHelper = $this->helper('Magento\GiftMessage\Helper\Message');
        $_giftMessage = $_giftMessageHelper->getGiftMessage($_quote->getGiftMessageId());
        ?>
        <?php if ($_giftMessage) : ?>
            <br/>
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= __('Gift Message for this Quote') ?></h3>
                        <strong><?= __('From:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br/><strong><?= __('To:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br/><strong><?= __('Message:'); ?></strong>
                        <br/><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
