<?php
use Cart2Quote\Quotation\Block\Quote\Email\Items\DefaultItems as B; /** @var B $block */ $b = $block; /** @var B $b */
use Magento\Catalog\Model\Product as P;
/** @var $b \Cart2Quote\Quotation\Block\Quote\Email\Items\DefaultItems */

/** @var $_item \Magento\Quote\Model\Quote\Item */
/** @var $_quote \Cart2Quote\Quotation\Model\Quote */
$_item = $b->getItem();
$p = $_item->getProduct(); /** @var P $p */
$_quote = $_item->getQuote();
?>
<tr>
	<td class="item-info<?php if ($b->getItemOptions()) : ?> has-extra<?php endif; ?>">
		<p class="product-name"><?php echo  $b->escapeHtml($_item->getName()) ?></p>
<?php
	# 2021-05-14 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
	# "`Cart2Quote_Quotation`: «Array to string conversion»
	# in `app/design/frontend/MageSuper/magestylish/Cart2Quote_Quotation/templates/email/proposal/items/quote/default.phtml`":
	# https://github.com/canadasatellite-ca/site/issues/107
	if ($v = $p->getResource()->getAttributeRawValue($p->getEntityId(), 'quote_description', 0)) { /** @var mixed $v */
		echo df_tag('p', 'product-description', $b->escapeHtml($v));
	}
?>
		<p class="sku"><?php echo  __('SKU'); ?>: <?php echo  $b->escapeHtml($b->getSku($_item)) ?></p>
		<?php if ($b->getItemOptions()) : ?>
			<dl class="item-options">
				<?php foreach ($b->getItemOptions() as $option) : ?>
					<dt><strong><em><?php echo  $option['label'] ?></em></strong></dt>
					<dd>
						<?php echo  nl2br($option['value']) ?>
					</dd>
				<?php endforeach; ?>
			</dl>
		<?php endif; ?>
		<?php $addInfoBlock = $b->getProductAdditionalInformationBlock(); ?>
		<?php if ($addInfoBlock) : ?>
			<?php echo  $addInfoBlock->setItem($_item)->toHtml() ?>
		<?php endif; ?>
		<?php echo  $b->escapeHtml($_item->getDescription()) ?>
	</td>
	<?php if (!$b->isProductRemarkDisabled()) : ?>
		<td class="item-comment">
			<?php
			$tierItem = $_item->getTierItems();
			foreach ($tierItem as $key => $val) {
				if ($val->getItemHasComment()) {
					echo $val->getComment();
				}
			}
			?>
		</td>
	<?php endif; ?>
	<td class="item-qty"><?php echo  $_item->getQty() * 1 ?></td>
	<td class="item-price">
		<?php
		$price = $_item->getCustomPrice();
		if ($price == null) {
			$price = $_item->getOriginalPrice();
		}
		?>
		&nbsp;<?php //echo  $_quote->formatPrice($price); ?>
	</td>
	<td class="item-price">
		<?php echo  $b->getItemPrice($_item); ?>
	</td>
</tr>
<?php
$_giftMessageHelper = $this->helper('Magento\GiftMessage\Helper\Message');
if ($_item->getGiftMessageId() && $_giftMessage = $_giftMessageHelper->getGiftMessage($_item->getGiftMessageId())) : ?>
	<tr>
		<td     colspan="3" class="item-extra">
			<table class="message-gift">
				<tr>
					<td>
						<h3><?php echo  __('Gift Message') ?></h3>
						<strong><?php echo  __('From:'); ?></strong> <?php echo  $b->escapeHtml($_giftMessage->getSender()) ?>
						<br/><strong><?php echo  __('To:'); ?></strong> <?php echo  $b->escapeHtml($_giftMessage->getRecipient()) ?>
						<br/><strong><?php echo  __('Message:'); ?></strong>
						<br/><?php echo  $b->escapeHtml($_giftMessage->getMessage()) ?>
					</td>
				</tr>
			</table>
		</td>
	</tr>
<?php endif; ?>
