<?php
/**
 * Cart2Quote
 */

/**
 * @var $block \Cart2Quote\Quotation\Block\Quote\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total) : ?>
    <?php if ($_total->getBlockName()) : ?>
        <?php echo $block->getChildHtml($_total->getBlockName(), false); ?>
    <?php else : ?>
        <tr class="<?php echo $_code ?>">
            <th <?php
            if (!$block->isProductRemarkDisabled()) {
                echo $block->getLabelPropertiesWithComment();
            } else {
                echo $block->getLabelProperties();
            }
            ?> scope="row">
                <?php if ($_total->getStrong()) : ?>
                    <strong><?php echo $block->escapeHtml($_total->getLabel()); ?></strong>
                <?php else : ?>
                    <?php echo $block->escapeHtml($_total->getLabel()); ?>
                <?php endif ?>
            </th>
            <td <?php echo $block->getValueProperties() ?>
                data-th="<?php echo $block->escapeHtml($_total->getLabel()); ?>">
                <?php if ($_total->getStrong()) : ?>
                    <strong><?php echo $block->formatValue($_total) ?></strong>
                <?php else : ?>
                    <?php echo $block->formatValue($_total) ?>
                <?php endif ?>
            </td>
        </tr>
    <?php endif ?>
<?php endforeach ?>
