<?php
use Interactivated\Quotecheckout\Block\Checkout\Onepage\Billing\Sortbilling as B;
/** @var B $block */ $b = $block; /** @var B $b */
$_dob = $b->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob');
$_gender = $b->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender');
$_taxvat = $b->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat');

$name = '';
$company = '';
$email = '';
$street = '';
$city = '';
$state = '';
$zipcode = '';
$country = '';
$telephone = '';
$fax = '';
$dob = '';
$gender = '';
$taxvat = '';

if ($_dob->isEnabled()) {
	$dob = $_dob->setDate($b->getQuote()->getCustomerDob())
		->setTemplate('MW_Onestepcheckout::customer/widget/dob.phtml')
		->setFieldIdFormat('billing:%s')
		->setFieldNameFormat('billing[%s]')
		->toHtml();
}
if ($_gender->isEnabled()) {
	$gender = '<div class="field">';
	$gender .= $_gender->setGender($b->getQuote()->getCustomerGender())
		->setTemplate('MW_Onestepcheckout::customer/widget/gender.phtml')
		->setFieldIdFormat('billing:%s')
		->setFieldNameFormat('billing[%s]')
		->toHtml();
	$gender .= '</div>';
}
if ($_taxvat->isEnabled()) {
	$taxvat = '<div class="field" id="mw_osc_taxvat">';
	$taxvat .= $_taxvat->setTaxvat($b->getQuote()->getCustomerTaxvat())
		->setTemplate('MW_Onestepcheckout::customer/widget/taxvat.phtml')
		->setFieldIdFormat('billing:%s')
		->setFieldNameFormat('billing[%s]')
		->toHtml();
	$taxvat .= '</div>';
}

$name = $b->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
	->setTemplate('Interactivated_Quotecheckout::customer/widget/name.phtml')
	->setObject($b->getAddress())
	->setFieldIdFormat('billing:%s')
	->setFieldNameFormat('billing[%s]')
	->toHtml();

$company = '<div class="field">
		<label for="billing:company"><em>' . $b->isStar('company') . '</em>' . __('Company') . '</label>
		<div class="input-box">
			<input type="text" id="billing:company" name="billing[company]" value="' . $b->escapeHtml($b->getAddress()->getCompany()) . '" title="' . __('Company') . '" class="input-text inputtext ' . $b->isRequired('company') . '" />
		</div>
	</div>';

$email = '<div class="field">
		<label for="billing:email"><em>*</em>' . __('Email Address') . '</label>
		<div class="input-box">
			<input type="text" name="billing[email]" id="billing:email" value="' . $b->escapeHtml($b->getCustomerSession()->getCustomer()->getEmail()) . '" title="' . __('Email Address') . '" ' . ($b->isCustomerLoggedIn() == true ? 'readonly="true"' : '') . ' class="input-text inputtext validate-email required-entry" />
		</div>
	</div>';
$password = $password_conf = '';
if (!$b->isCustomerLoggedIn()):
	$createAccountConfig = (int)df_cfg('onestepcheckout/general/create_account');
	if ($createAccountConfig == 1) {
		$attributes = 'style="display:block;"';
	} else {
		$attributes = 'style="display:none;"';
	}
	$password = '
		<div class="field" id="register-customer-password" '. $attributes .'>
			<label for="billing:customer_password" class="required"><em>*</em>'. __('Password') .'</label>
			<div class="input-box">
				<input type="password" name="billing[customer_password]" id="billing:customer_password" title="'.__('Password').'" class="input-text inputtext required-entry validate-password" />
			</div>
		</div>
	';
	$password_conf = '
		<div class="field"  id="register-customer-password-conf" '. $attributes .'>
			<label for="billing:confirm_password" class="required"><em>*</em>'.__('Confirm Password').'</label>
			<div class="input-box">
				<input type="password" name="billing[confirm_password]" title="'.__('Confirm Password').'" id="billing:confirm_password" class="input-text inputtext required-entry validate-cpassword" />
			</div>
		</div>
	';
endif;

$streetValues = $b->getAddress()->getStreet();
$val_street_1 = $streetValues[0];
if ($val_street_1 == 'n/a') {
	$val_street_1 = '';
}
$street = '<div>
	<ul>
		<li class="wide">
			<label for="billing:street1"><em>' . $b->isStar('street') . '</em>' . __('Address') . '</label>
			<div class="input-box">
				<input type="text" title="' . __('Street Address') . '" name="billing[street][]" id="billing:street1" value="' . $b->escapeHtml($val_street_1) . '" class="input-text inputtext  ' . $b->isRequired('street') . '" />
			</div>
		</li>';

for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++) {
	if (isset($streetValues[$_i - 1])) {
		$temp_address = $streetValues[$_i - 1];
		if($temp_address =='n/a') {
			$temp_address = '';
		}
	} else {
		$temp_address = '';
	}

	$street = $street . '<li class="wide">
							<div class="input-box">
								<input type="text" title="' . __('Street Address %1', $_i) . '" name="billing[street][]" id="billing:street' . $_i . '" value="' . $b->escapeHtml($temp_address) . '" class="input-text inputtext" />
							</div>
						</li>';
}
$street = $street . '</ul></div>';

$vat_id = '';
$_addressHelper = $this->helper('Magento\Customer\Helper\Address');
if ($_addressHelper->isVatAttributeVisible()) {
	$vat_id = '<li class="wide" id="osc_shipping_vat_id">
		<label for="billing:vat_id">'.__('VAT Number').'</label>
		<div class="input-box">
			<input type="text" id="billing:vat_id" name="billing[vat_id]" value="'.$b->escapeHtml($b->getAddress()->getVatId()).'" title="'.__('VAT Number').'" class="input-text '.$_addressHelper->getAttributeValidationClass('vat_id').'" />
		</div>
	</li>';
}

$cityval = $b->getAddress()->getCity();
if ($cityval == 'n/a') {
	$cityval = '';
}
$city = '<div class="field">
		<label for="billing:city"><em>' . $b->isStar('city') . '</em>' . __('City') . '</label>
		<div class="input-box">
			<input type="text" title="' . __('City') . '" name="billing[city]" value="' . $b->escapeHtml($cityval) . '" class="input-text inputtext  ' . $b->isRequired('city') . '" id="billing:city" />
		</div>
	</div>';

$region = $b->getAddress()->getRegion();
$regionidval = (isset($region['region_id'])) ? $region['region_id'] : '';
$regionval = (isset($region['region'])) ? $region['region'] : '';
$state = '<div class="field">
		<label for="billing:region_id"><em>' . $b->isStar('state') . '</em>' . __('Province / State') . '</label>
		<div class="input-box billing_region_class">
			<select id="billing:region_id" name="billing[region_id]" title="' . __('Province / State') . '" ' . ((df_cfg("onestepcheckout/addfield/state") == 1) ? 'class="validate-select" ' : ' ') . 'style="display:none;">
				<option value="">' . __('Please select region, state or province') . '</option>
			</select>

			<script type="text/javascript">
				require([
					"jquery"
				], function($) {
					//<![CDATA[
						$("#billing:region_id").attr("defaultValue",  "' . $regionidval . '");
					//]]>
				});
			</script>

			<input type="text" id="billing:region" name="billing[region]" value="' . $b->escapeHtml($regionval) . '"  title="' . __('Province / State') . '" class="input-text inputtext  ' . $b->isRequired('state') . '" style="display:none;" />
		</div>
	</div>';

$postcodeval = $b->getAddress()->getPostcode();
if ($postcodeval == '.') {
	$postcodeval = '';
}
$zipcode = '<div class="field" id="field_zipcode">
		<label for="billing:postcode"><em>' . $b->isStar('zip') . '</em>' . __('Postal / ZIP Code') . '</label>
		<div class="input-box">
			<input type="text" title="' . __('Zip/Postal Code') . '" name="billing[postcode]" id="billing:postcode" value="' . $b->escapeHtml($postcodeval) . '" class="input-text inputtext validate-zip-international canadian-postcode ' . $b->isRequired('zip') . '" />
		</div>
	</div>';


$country = '<div class="field" id="field_country"' . ((df_cfg("onestepcheckout/addfield/country") == 0) ? 'style="display:none"' : '') . '>
		<label for="billing:country_id"><em>' . $b->isStar('country') . '</em>' . __('Country') . '</label>
		<div class="input-box">
			' . $b->getCountryHtmlSelect('billing') . '
		</div>
	</div>	';

$telephone = '<div class="field">
		<label for="billing:telephone"><em>' . $b->isStar('telephone') . '</em>' . __('Phone') . '</label>
		<div class="input-box">
			<input style="width: 100%;" type="text" name="billing[telephone]" value="' . $b->escapeHtml($b->getAddress()->getTelephone()) . '" title="' . __('Phone') . '" class="input-text inputtext  ' . $b->isRequired('telephone') . '" id="billing:telephone" />
		</div>
	</div>';

$fax = '<div class="field">
		<label for="billing:fax"><em>' . $b->isStar('fax') . '</em>' . __('Fax') . '</label>
		<div class="input-box">
			<input type="text" name="billing[fax]" value="' . $b->escapeHtml($b->getAddress()->getFax()) . '" title="' . __('Fax') . '" class="input-text inputtext  ' . $b->isRequired('fax') . '" id="billing:fax" />
		</div>
	</div>';

$typeAddress = [
	'company',
	'email',
	'street',
	'city',
	'state',
	'zip',
	'country',
	'telephone',
	'fax',
	'dob',
	'gender',
	'taxvat',
	'vat_id'
];
$billingBlock = ["", "", "", "", "", "", "", "", "", "", "", "",""];
$temp = [];
$notdisable = ['name'];
$filter = [];

foreach ($typeAddress as $nametype) {
	if ($nametype == 'email') {
		$notdisable[] = 'email';
		$notdisable[] = 'password';
		$notdisable[] = 'password_conf';
	} else {
		if (!$b->isDisable($nametype)) {
			$notdisable[] = $nametype;
		}
	}
}
foreach ($notdisable as $namevalid) {
	if ($namevalid == 'vat_id') {
		$filter[] = df_cfg('onestepcheckout/options_sort/sort_city') + 1;
	} else {
		$filter[] = df_cfg('onestepcheckout/options_sort/sort_' . $namevalid);
	}
}

for ($i = 0; $i < count($filter); $i++) {
	for ($j = $i + 1; $j < count($filter); $j++) {
		if ($filter[$i] == $filter[$j]) {
			$temp[] = $filter[$i];
			break;
		}
	}
}
$temp[] = df_cfg('onestepcheckout/options_sort/sort_name');

$nameinputs = [
	'name'=> $name,
	'company' => $company,
	'email' => $email,
	'password' => $password,
	'password_conf' => $password_conf,
	'street' => $street,
	'city' => $city,
	'state' => $state,
	'zip' => $zipcode,
	'country' => $country,
	'telephone' => $telephone,
	'fax' => $fax,
	'dob' => $dob,
	'gender' => $gender,
	'taxvat' => $taxvat,
	'vat_id' => $vat_id
];
foreach ($nameinputs as $nameadd => $bitem) {
	if (!in_array($nameadd, $notdisable)) {
		continue;
	}

	if (!in_array(df_cfg('onestepcheckout/options_sort/sort_' . $nameadd), $temp)) {
		if ($nameadd == 'dob') {
			$billingBlock[df_cfg('onestepcheckout/options_sort/sort_' . $nameadd)] = $billingBlock[df_cfg('onestepcheckout/options_sort/sort_' . $nameadd)] . $bitem;
		} else {
			$res = '';
			if(isset($billingBlock[df_cfg('onestepcheckout/options_sort/sort_' . $nameadd)])){
				$res = $billingBlock[df_cfg('onestepcheckout/options_sort/sort_' . $nameadd)];
			}
			$billingBlock[df_cfg('onestepcheckout/options_sort/sort_' . $nameadd)] = '<div class="widthfull">' . $res . $bitem . '</div>';
		}
	}else if ($nameadd == 'vat_id'){
		$billingBlock[1] = $bitem;
	} else {
		$billingBlock[df_cfg('onestepcheckout/options_sort/sort_' . $nameadd)] = $billingBlock[df_cfg('onestepcheckout/options_sort/sort_' . $nameadd)] . $bitem;
	}
}

$str = '';//'<div class="clear"></div><li class="fields">' . $name . '</li>';
foreach ($billingBlock as $bitem) {
	if ($bitem == "") {
		continue;
	}

	if ($bitem == 'dob') {
		$str = $str . '<div class="clear"></div><li class="fields"><div class="field">' . $bitem . '</div></li>';
	} else {
		$str = $str . '<div class="clear"></div><li class="fields">' . $bitem . '</li>';
	}
}

// Add country but hidden when disable contry
if (!df_cfg("onestepcheckout/addfield/country")) {
	$str = $str . '<div class="clear"></div><li class="fields">' . $country . '</li>';
}

if ($b->isDisable('state')) {
	$str = $str . '<div style="display:none;"><select id="billing:region_id" name="billing[region_id]"></select>
	<input type="text" id="billing:region" name="billing[region]" style="display:none;" /></div>
	';
}

echo $str;
?>

<script type="text/x-magento-init">
	{
		"#billing\\:country_id": {
			"regionUpdater": {
				"optionalRegionAllowed": <?php echo($b->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
				"regionListId": "#billing\\:region_id",
				"regionInputId": "#billing\\:region",
				"postcodeId": "#billing\\:postcode",
				"regionJson": <?php echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
				"defaultRegion": "<?php echo $b->getAddress()->getRegionId() ?>",
				"countriesWithOptionalZip": <?php echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
			}
		}
	}
</script>
<script type="text/javascript">
//<![CDATA[
	require([
		'jquery',
		'Magento_Customer/js/model/customer',
		'Magento_Customer/js/action/check-email-availability',
		'mage/url',
	], function($,customer,checkEmailAvailability,url){
		url.setBaseUrl('<?php echo $b->getBaseUrl();?>');
		var casatEmailCheck = {
			email: false,
			emailFocused: false,
			isLoading: false,
			isPasswordVisible: false,
			checkDelay: 2000,
			checkRequest: null,
			isEmailCheckComplete: null,
			isCustomerLoggedIn: customer.isLoggedIn,
			emailCheckTimeout: 0,
			validateRequest: function () {
				if (this.checkRequest != null && $.inArray(this.checkRequest.readyState, [1, 2, 3])) {
					this.checkRequest.abort();
					this.checkRequest = null;
				}
			},
			checkEmailAvailability: function () {
				var self = this;
				this.validateRequest();
				this.isEmailCheckComplete = $.Deferred();
				this.isLoading = true;
				this.checkRequest = checkEmailAvailability(this.isEmailCheckComplete, this.email);

				$.when(this.isEmailCheckComplete).done(function () {
					self.isPasswordVisible = false;
				}).fail(function () {
					self.isPasswordVisible = true;
					$('#mw-login-email').val(self.email);
					$('#loginbox').trigger('click');
				}).always(function () {
					self.isLoading = false;
				});
			},
		};
		$('#mw_onstepcheckout_billing_form input[id="billing\:email"]').on('change',function(){
			casatEmailCheck.email = $(this).val();
			casatEmailCheck.checkEmailAvailability();
		});
	});
//]]>
</script>
