<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_element = $block->getElement() ?>
<?php $_jsObjectName = $block->getFieldSetId() != null ? $block->getFieldSetId() : $_element->getHtmlId() ?>

<div class="rule-tree">
    <fieldset id="<?= $block->escapeHtml($_jsObjectName) ?>" <?= $block->escapeHtml($_element->serialize(['class'])) ?> class="fieldset">
        <div class="rule-tree-wrapper">
            <?= $_element->getChildrenHtml() ?>
        </div>
        <div class="help-and-general">
            <span><?= $block->escapeHtml($_element->getLegend()) ?></span>
        </div>
    </fieldset>
</div>

<script>
    require([
        "Magento_Rule/rules",
        "prototype"
        ], function(VarienRulesForm) {

            window.<?php /* @escapeNotVerified */ echo $_jsObjectName ?> = new VarienRulesForm('<?php /* @escapeNotVerified */ echo $_jsObjectName ?>', '<?php /* @escapeNotVerified */ echo $block->getNewChildUrl() ?>');
        }
    );
</script>