<?php
/**
 * Copyright © Mageside. All rights reserved.
 * See MS-LICENSE.txt for license details.
 */

/** @var Mageside\CanadaPostShipping\Block\Offices $block */
?>
<?php if ($block->canShowD2po()): ?>
    <div id="canadapost-find-offices-map" class="canadapost-map-modal" style="display:none;">
        <div class="messages"></div>
        <div class="content-modal content-wrapper">
            <aside class="offices-list">
                <nav>
                    <ul></ul>
                </nav>
            </aside>
            <div id="canadapost-map" class="map-content">
                <div class="messages">
                    <div class="message-error error message">
                        <div><?= /* @escapeNotVerified */ __('Something went wrong while loading Google Maps.') ?></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php if ($apiKey = $block->getGoogleMapsApiKey()): ?>
        <script>
            require([
                'async!https://maps.googleapis.com/maps/api/js?key=<?= $block->escapeHtml($apiKey) ?>'
            ], function () {});
        </script>
    <?php endif; ?>
<?php endif; ?>

