<?php
/**
 * @category   Mageants AlsoBought
 * @package    Mageants_AlsoBought
 * @copyright  Copyright (c) 2017 Mageants
 * @author     Mageants Team <support@Mageants.com>
 */
$products = $this->getProductCollection();
if(count($products)):
$displayAddToCart = $this->getConfig('alsobought_section/alsobought_product/alsobought_product_cart_button');

echo $this->getConfig('alsobought_section/alsobought_product/alsobought_product_title') ? '<h2>'.__($this->getConfig('alsobought_section/alsobought_product/alsobought_product_title')).'</h2>':''; 
if($this->getConfig('alsobought_section/alsobought_product/alsobought_product_layout') == "slider"){?>
        <script>
        require([
            'jquery',
            'OwlCarousel'
        ], function () {
            'use strict';
            jQuery.noConflict();
            jQuery(".owl-carousel").owlCarousel({
                items : <?php echo $this->getConfig('alsobought_section/slider_settings/slider_items') ? $this->getConfig('alsobought_section/slider_settings/slider_items') : 3 ?>,
                loop: <?php echo $this->getConfig('alsobought_section/slider_settings/slider_loop') ?>,
                dots: <?php echo $this->getConfig('alsobought_section/slider_settings/slider_dots') ?>,
                nav:<?php echo $this->getConfig('alsobought_section/slider_settings/slider_nav') ?>,
                center:true
            });
        });
    </script>
    <div class="columns">
    <div id="owl-demo" class="owl-carousel owl-theme"">
    <?php }else{ ?>
    <div class="products wrapper grid products-grid">
    <?php } ?>
        <?php foreach ($products as $product) { ?>
            <div class="product-item">
            <div class="product-item-info" data-container="product-grid" style="text-align: center;margin: 0 auto;">
                    <?php
                    $imageBlock =  $this->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
                    $productImage = $imageBlock->getImage($product, 'category_page_list'); ?>
                    <a href="<?php /* @escapeNotVerified */ echo $product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                         <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $product->getName(); ?>
                            </a>
                        </strong>
                        <?php /* @escapeNotVerified */ echo $this->getProductPrice($product) ?>
                        <?php if($displayAddToCart){ ?>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions">
                                    <?php if ($product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($product); ?>
                                       <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">

                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>
<?php endif; ?>