<?php

$_dataHelper = $this->helper('MW\Onestepcheckout\Helper\Data');
if ($_dataHelper->getStoreConfig('onestepcheckout/general/enable_geoip')) :
    if($block->getSessionManager()->getCity()) {
        $cityval = $block->getSessionManager()->getCity();
    } else {
        $cityval = $block->getRegistry()->registry('City');
    }

    if($block->getSessionManager()->getRegionId()) {
        $regionidval = $block->getSessionManager()->getRegionId();
    } else {
        $regionidval = $block->getRegistry()->registry("Regionid");
    }

    if($block->getSessionManager()->getRegion()) {
        $regionval = $block->getSessionManager()->getRegion();
    } else {
        $regionval = $block->getRegistry()->registry('Regionname');
    }

    if($block->getSessionManager()->getPostcode()) {
        $postcodeval = $block->getSessionManager()->getPostcode();
    } else {
        $postcodeval = $block->getRegistry()->registry('Zipcode');
    }
?>

	<script type="text/javascript">
		require([
			'jquery'
		], function($) {
			isLogged = <?php echo ($block->getCustomerSession()->isLoggedIn() ? 1 : 0) ?>;
		    var ip = "<?php echo getenv('REMOTE_ADDR') ?>";

		    // Geoip for form
		    window.geoip = {};
		    window.geoip.postcode = '<?php echo $postcodeval?>';
		    window.geoip.city = '<?php echo $cityval?>';
		    window.geoip.region = '<?php echo $regionval?>';
		    window.geoip.regionid = '<?php echo $regionidval?>';
		});
	</script>

<?php endif; ?>

<?php if ($_dataHelper->getStoreConfig('onestepcheckout/general/enabled')) : 
    $design = $_dataHelper->getStoreConfig('onestepcheckout/display_setting/style');
    $roundCorner = $_dataHelper->getStoreConfig('onestepcheckout/display_setting/round_corner');
?>
	<?php if ($design == 2 || $design == 3) : ?>
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('MW_Onestepcheckout::css/onestepcheckout_flat.css') ?>" />

        <?php if($design == 3) : ?>
            <link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('MW_Onestepcheckout::css/onestepcheckout_classic.css') ?>" />
        <?php endif; ?>

        <?php if ($roundCorner == 1) : ?>
            <link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('MW_Onestepcheckout::css/onestepcheckout_corner.css') ?>" />
         <?php endif; ?>
    <?php endif; ?>

    <?php echo $_dataHelper->renderConfigCss(); ?>
    <?php echo $_dataHelper->renderConfigJs(); ?>

    <script type="text/javascript" src="<?php echo $block->getViewFileUrl('MW_Onestepcheckout::js/view.js') ?>"></script>
<?php endif; ?>

<script type="text/javascript">
	isLogged = <?php echo ($block->getCustomerSession()->isLoggedIn() ? 1 : 0) ?>;
</script>