<?php
use Mageplaza\Blog\Block\Post\View as B; /** @var B $block */ $b = $block; /** @var B $b */
use Mageplaza\Blog\Model\Post;
use Mageplaza\Blog\Model\ResourceModel\Post\Collection as PostC;
$_post = $b->getCurrentPost(); /** @var Post $_post */
$author = $b->getAuthorByPost($_post->getAuthorId());
$authorName = $author !== null ? $author->getName() : '';
$modifier = $b->getAuthorByPost($_post->getModifierId());
$modifierName = $modifier !== null ? $modifier->getName() : '';
$checkRss = $b->checkRss();
if ($checkRss) {
	?>
	<div class="mp-blog-rss">
		<a href="<?= $checkRss ?>" class="bb-rss-icon">
			<img src="<?= $this->getViewFileUrl('Mageplaza_Blog::media/images/rss.png') ?>" width="16px" />
		</a>
	</div>
<?php }
if ($b->filterPost($_post)): ?>
	<?php if ($b->getBlogConfig('share/enabled')) { ?>
		<script
			async="async"
			src="//s7.addthis.com/js/300/addthis_widget.js#pubid=<?= $b->getBlogConfig('share/pubid_id') ?>"
			type="text/javascript"
		></script>
	<?php } ?>
	<div class="mpcss post-view" id="mpblog-list-container">
		<div class="row">
			<?php if (1 == $b->getBlogConfig('sidebar/sidebar_left_right')) { ?>
				<div class="col-md-9 col-sm-6">
					<div class="post-image col-xs-12">
					   <?php if ($_post->getImage()) { ?>
						   <a
							   class="fancybox"
							   href="<?= $b->getImageUrl($_post->getImage()); ?>"
						   >
							   <img
								   alt="<?= $b->escapeHtml($_post->getName()); ?>"
								   class="img-responsive"
								   src="<?= $b->getImageUrl($_post->getImage()); ?>"
							   />
						   </a>
					   <?php } ?>
					</div>
					<div class="post-post_content col-xs-12"><?= $b->getPageFilter($_post->getPostContent()); ?></div>
					<div class="col-xs-12">
						<hr/>
						<div class="mp-post-info">
							<span><i class="fa fa-calendar-times-o"></i> <?= $b->getDateFormat($_post->getCreatedAt()); ?></span>
							<?php if ($b->getPostCategoryHtml($_post)) { ?>
								| <span><i class="fa fa-folder-open-o"></i>
								<?= __('Categories:') . ' ' . $b->getPostCategoryHtml($_post); ?> </span>
							<?php } ?>
							<?php if ($b->getTagList($_post)) { ?>
								| <span><i class="fa fa-tags"></i> <?= __('Tags:') . ' ' . $b->getTagList($_post); ?></span>
							<?php } ?>
							<?php if ($authorName && $b->getBlogConfig('general/display_author')){ ?>
								| <span><i class="fa fa-user"></i> By: <a class="mp-info" href="<?= $b->getAuthorUrl($author) ?>"><?= $authorName; ?></a></span>
								<?php if ($authorName != $modifierName && $modifierName){ ?>
									| <span><i class="fa fa-edit"></i> Modify By: <a class="mp-info" href="<?= $b->getAuthorUrl($modifier) ?>"><?= $modifierName;?></a><?= ' at : '.$_post->getUpdatedAt(); ?></span>
								<?php } ?>
							<?php } ?>

						</div>
						<hr/>
					</div>
				</div>

			<div class="mp-sidebar col-md-3 col-sm-6">
					<?= $this->getChildHtml(); ?>
			</div>
				<?php
			}else{ ?>

				<div class="mp-sidebar col-md-3 col-sm-6">
					<?= $this->getChildHtml(); ?>
				</div>

				<div class="col-md-9 col-sm-6">

					<div class="post-image col-xs-12">
					   <?php if ($_post->getImage()) : ?>
						   <a class="fancybox" href="<?= $b->getImageUrl($_post->getImage()); ?>">
							   <img class="img-responsive" src="<?= $b->getImageUrl($_post->getImage()); ?>" alt="<?= $b->escapeHtml($_post->getName()); ?>"/>
						   </a>
					   <?php endif; ?>
					</div>


					<div class="post-post_content col-xs-12">
						<?= $b->getPageFilter($_post->getPostContent()); ?>
					</div>

					<div class="col-xs-12">
						<hr/>
						<div class="mp-post-info">
							<span><i class="fa fa-calendar-times-o"></i> <?= $b->getDateFormat($_post->getCreatedAt()); ?></span>
							<?php if ($b->getPostCategoryHtml($_post)) {?>
								| <span><i class="fa fa-folder-open-o"></i> <?= __('Categories:'); ?> <?= $b->getPostCategoryHtml($_post); ?> </span>
							<?php } ?>
							<?php if ($b->getTagList($_post)) {?>
								| <span><i class="fa fa-tags"></i> <?= __('Tags:'); ?>  <?= $b->getTagList($_post); ?></span>
							<?php } ?>

							<?php if ($authorName && $b->getBlogConfig('general/display_author')){ ?>
								| <span><i class="fa fa-user"></i> By: <a class="mp-info" href="<?= $b->getAuthorUrl($author) ?>"><?= $authorName; ?></a></span>
							<?php if ($authorName != $modifierName && $modifierName){ ?>
									| <span><i class="fa fa-edit"></i> Modify By: <a class="mp-info" href="<?= $b->getAuthorUrl($modifier) ?>"><?= $modifierName;?></a><?= ' at : '.$_post->getUpdatedAt(); ?></span>

								<?php } ?>
							<?php } ?>

						</div>
						<hr/>
					</div>
				</div>

			<?php }?>
		</div>
	</div>


<?php if ($b->getBlogConfig('share/enabled')): ?>
	<div class="mpcss">
		<div id="sharing">
			<div class="share-col-left">
				<h5><?= __('Share this post, Hit on social buttons!'); ?></h5>
			</div>
			<div class="share-col-right">
				<div class="post-sharing-button">
						<div class="addthis_sharing_toolbox"></div>
				</div>
			</div>
		</div>
	</div>
<?php endif; ?>

<?php
if($b->getBlogConfig('general/display_author') && $b->getBlogConfig('general/author_description')): ?>
	<div class="mpcss about-admin">
		<div class="row">
			<div class="col-xs-12 author-title">
				<h4 class="admin-title"><?= __('About the Author: ');?><a class="mp-info"><?php if($b->getBlogConfig('general/author_name')) echo $b->getBlogConfig('general/author_name');?></a></h4>
				<div id="admin-border"></div>
			</div>
			<div class="col-xs-12 author-des">
				<?php if($b->getBlogConfig('general/upload_image')):?>
				<div class="admin-avatar">
					<img class="img-responsive" src="<?= $b->getImageUrl('mageplaza/author/'.$b->getBlogConfig('general/upload_image'));?>">
				</div>
				<?php endif;?>
				<div class="admin-description">
					<?= $b->getBlogConfig('general/author_description');?>
<!--					--><?php //echo $b->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mageplaza_blog_author_admin')->toHtml(); ?>
				</div>
			</div>
		</div>
	</div>
<?php endif;?>

<?php
	$relatedPosts = $_post->getRelatedPostsCollection(); /** @var PostC|null $relatedPosts */
	$countRelated = 0;
	$limitRelated = $b->getBlogConfig('general/related_post');
	# 2021-03-27 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
	# «count(): Parameter must be an array or an object that implements Countable
	# in app/code/Mageplaza/Blog/view/frontend/templates/post/view.phtml on line 185»:
	# https://github.com/canadasatellite-ca/site/issues/50
	if ($relatedPosts && count($relatedPosts)): ?>

	<div class="post-same-topics topic-list mpcss">
		<div class="row">
			<div class="col-xs-12 row">
					<h2><?= ($limitRelated) ? __('Related Posts') : __(''); ?></h2>
					<?php foreach ($relatedPosts as $relatedPost): ?>
						<?php
							if($b->filterPost($relatedPost)):
								$countRelated++;
							?>
								<?php if($countRelated > $limitRelated) break; ?>
						<div class="relate-content item col-xs-3" style="margin-right:10px;">
							<a class="mp-relate-link" href="<?= $b->getUrlByPost($relatedPost) ?>">
								<?php if ($relatedPost->getImage()){ ?>
								<img class="img-responsive" src="<?= $b->getImageUrl($relatedPost->getImage()); ?>" align="middle" alt="<?= $b->escapeHtml($relatedPost->getName()); ?>">
								<?php } else {?>
									<img class="img-responsive" src="<?= $b->getDefaultImageUrl() ?>"align="middle" alt="<?= $b->escapeHtml($relatedPost->getName()); ?>">
								<?php }?>
								<?= $relatedPost->getName(); ?>
							</a>
						</div>
							<?php endif; ?>
					<?php endforeach; ?>
			</div>
		</div>
	</div>

<?php endif; ?>
<div class="mpcss mp-comment">
	<?php if( $_post->getAllowComment()==1) { ?>
		<?php $typeComment = $b->checkComment(); ?>
		<?php if ($typeComment == Mageplaza\Blog\Model\Config\Source\Comments\Type::DISQUS): ?>
			<div class="box-collateral box-reviews" id="post-reviews">
				<h2><?= __('Comments') ?></h2>

				<div id="disqus_thread"></div>
				<script type="text/javascript">
					var disqus_shortname = '<?= $b->helperComment('disqus');?>';

					/* * * DON'T EDIT BELOW THIS LINE * * */
					(function () {
						var dsq = document.createElement('script');
						dsq.type = 'text/javascript';
						dsq.async = true;
						dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
						(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
					})();
				</script>


			</div>
		<?php elseif ($typeComment == Mageplaza\Blog\Model\Config\Source\Comments\Type::FACEBOOK): ?>
			<div class="box-collateral box-reviews" id="post-reviews">
				<h2><?= __('Comments') ?></h2>

				<div id="fb-root"></div>
				<script>(function (d, s, id) {
						var js, fjs = d.getElementsByTagName(s)[0];
						if (d.getElementById(id)) return;
						js = d.createElement(s);
						js.id = id;
						js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.5&appId=<?= $this->getAppId()?>";
						fjs.parentNode.insertBefore(js, fjs);
					}(document, 'script', 'facebook-jssdk'));</script>


				<div class="fb-comments" data-href="<?= $b->getUrlByPost($_post); ?>" data-numposts="<?= $b->helperComment('facebook_number_comment'); ?>"
					 data-width="100%" data-colorscheme="<?= $b->helperComment('facebook_colorscheme') ?>" data-order-by="<?= $b->helperComment('facebook_order_by') ?>"></div>

			</div>

		<?php elseif ($typeComment == Mageplaza\Blog\Model\Config\Source\Comments\Type::DEFAULT_COMMENT): ?>
			<div class="container default-cmt">
				<div class="row">
					<div class="col-xs-10"> <h2><?= __('Comments'); ?></h2></div>
					<div class="col-xs-2">
						<div class="default-cmt__cmt-login" <?php if ($b->isLoggedIn()) {echo 'style="display:none;"';} ?>>
							<button class="btn-primary default-cmt__cmt-login__btn-login"><?= __('Login') ?></button>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12">
						<div class="default-cmt__content">
							<?php
							/**
							 * Comment box
							 */
							 ?>
							<div class="default-cmt__content__cmt-block">
								<div class="default-cmt__content__cmt-block__cmt-box">
									<textarea class="default-cmt__content__cmt-block__cmt-box__cmt-input" maxlength="255" placeholder="<?= __('Type comments here...') ?>"></textarea>
									<div class="default-cmt__content__cmt-block__cmt-box__cmt-btn">
										<button class="default-cmt__content__cmt-block__cmt-box__cmt-btn__btn-submit btn-primary" <?php if (!$b->isLoggedIn()) {echo ' disabled';} ?>><?= __('Comment') ?></button>
									</div>
								</div>
							</div>

							<div class="default-cmt__content__cmt-content">
							<?php
							/**
							 * Comment rows
							 */
							$comments = $b->getPostComments($_post->getId());
							$b->getCommentsTree($comments, 0);
							$html = $b->getCommentsHtml();
							echo $html;
							?>
							</div>
						</div>
					</div>
				</div>
			</div>

			<script>
				//get login url, text of button like, reply
				var loginUrl = '<?= $b->getLoginUrl(); ?>';
				var like = '<?= __('Like') ?>',
					reply = '<?= __('Reply') ?>';

				require([
					'comment'
				]);
			</script>

		<?php endif;
	}?>
</div>
<script>
	less = {
		async: false,
		dumpLineNumbers: "comments",
		env: "production",
		fileAsync: false,
		functions: {},
		logLevel: 2,
		modifyVars: {'@color': '<?= $b->getBlogConfig('general/font_color')?>'}
		poll: 1000,
		relativeUrls: false,
		useFileCache: true
	};
</script>
<script>require(['jquery', 'Mageplaza_Blog/js/lib/less.min']);</script>
<?php
	/**
	 * Seo article snippet
	 */
	$enableSnippet = $b->getSeoConfig('snippet/enabled');
	$orgName = $b->getSeoConfig('snippet/organize_name');
	$logo = $b->getSeoConfig('snippet/upload_image_id') ? $b->getLogoImage($b->getSeoConfig('snippet/upload_image_id'))
		: $b->getDefaultImageUrl();

	if ($enableSnippet):
?>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "NewsArticle",
  "mainEntityOfPage": {
	"@type": "WebPage",
	"@id": "https://google.com/article"
  },
  "headline": "<?= $_post->getName(); ?>",
  "image": {
	"@type": "ImageObject",
	"url": "<?= $_post->getImage() ? $b->getImageUrl($_post->getImage())
		: $b->getDefaultImageUrl(); ?>",
	"height": 800,
	"width": 800
  },
  "datePublished": "<?= $b->getDateFormat($_post->getCreatedAt()); ?>",
  "dateModified": "<?= $b->getDateFormat($_post->getUpdatedAt()); ?>",
  "author": {
	"@type": "Person",
	"name": "<?= $authorName; ?>"
  },
   "publisher": {
	"@type": "Organization",
	"name": "<?= $orgName; ?>",
	"logo": {
	  "@type": "ImageObject",
	  "url": "<?= $logo; ?>",
	  "width": 600,
	  "height": 60
	}
  },
  "description": "<?= $_post->getShortDescription(); ?>"
}
</script>

	<?php endif; ?>

<?php else: ?>
	<div><?= __('This store has no post with name: ').$_post->getName() ?></div>

<?php endif;?>

<script type="text/javascript">
	require([
		'jquery',
		'fancybox',
		'migrate'
	], function($){
		var addToAll = false;
		var gallery = true;
		var titlePosition = 'inside';
		$(addToAll ? 'img' : 'img.fancybox').each(function(){
			var $this = $(this);
			var title = $this.attr('title');
			var src = $this.attr('data-big') || $this.attr('src');
			var a = $('<a href="#" class="fancybox"></a>').attr('href', src).attr('title', title);
			$this.wrap(a);
		});
		if (gallery)
			$('a.fancybox').attr('rel', 'fancyboxgallery');
		$('a.fancybox').fancybox({
			titlePosition: titlePosition
		});
	});
</script>
