<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="help-and-general-form">
    <?= $block->escapeHtml(__('Control how your product catalog interacts with the Amazon marketplace')) ?>
</div>
<div id="listing-condition-attribute-url" style="display:none" data-storeurl="<?= $block->escapeHtml($block->getUrl('channel/amazon/account_settings_listings_attributes')) ?>"></div>
