<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="order-payment-method-name"><?= $block->escapeHtml($block->getMethod()->getTitle()); ?></div>
<table class="data-table admin__table-secondary">
    <tr>
        <th><?= $block->escapeHtml(__('Amazon Order Number')); ?>:</th>
        <td><?= $block->escapeHtml($block->getInfo()->getPoNumber()); ?></td>
    </tr>
    <tr>
        <th>
            <a href="<?= $block->escapeHtml($block->getOrderDetailsUrl()) ?>" target="_blank">
                <?= $block->escapeHtml('View or Cancel Amazon Order') ?>
            </a>
        </th>
    </tr>
</table>
