<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2016] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Cart2Quote
 * @package     Desk
 * @copyright   Copyright (c) 2016 Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var Cart2Quote\Desk\Block\Magento\Contact\Success $block */
?>

<div class="form contact ticket-form-success-content" style="display:none;">
    <fieldset class="fieldset ticket-fieldset review-fieldset" data-hasrequired="<?php __("* Required Fields"); ?>">
        <legend class="legend review-legend ticket-legend">
            <span><?php echo __("Thank you for your question."); ?></span>
        </legend>
        <br/>
        <div class="actions-toolbar review-form-actions ticket-success-form-actions">
            <div class="primary actions-primary">
                <button type="submit"
                        class="action submit primary"
                        id="view-ticket-button"
                        data-ticket-id="0"
                        data-mage-init='{
                            "desk.view.ticket.button" : {
                                "bindOnClick": "1",
                                "url": "<?php echo $this->getUrl('desk/customer/view') ?>"
                            }
                        }'>
                    <span><?php echo __("View your ticket") ?></span>
                </button>
                <br/><br/>
                <button type="submit"
                        class="action submit"
                        data-mage-init='{ "desk.view.form.button" : {} }'>
                    <span><?php echo __("Ask a new question") ?></span>
                </button>
            </div>
        </div>
    </fieldset>
</div>
