<?php
/**
 * Cart2Quote
 */
?>
<script>
    require(["Magento_Sales/order/create/form"], function () {
        var submitAction = order.submit;
        var form = jQuery("#edit_form");
        var actionUrl = form.attr("action");

        order.quoteSubmit = function () {
            form.attr("action", "<?php echo $this->getSaveUrl() ?>");
            submitAction();
        }
        order.submit = function () {
            form.attr("action", actionUrl);
            submitAction();
        }
    });
</script>
<div class="fieldset-wrapper-title">
    <div class="actions"><?php echo $block->getButtonsHtml() ?></div>
</div>

<?php echo $block->getChildHtml('', true) ?>
